package edu.unindra.kkp_kelompok4.report;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import edu.unindra.kkp_kelompok4.Services.serviceReport;
import edu.unindra.kkp_kelompok4.Services.serviceTypeItem;
import edu.unindra.kkp_kelompok4.dao.DAO_Report;
import edu.unindra.kkp_kelompok4.dao.DAO_typeItem;
import edu.unindra.kkp_kelompok4.model.modelTypeItem;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ripal
 */
public class reportItem extends javax.swing.JPanel {
    
	private serviceReport reportService = new DAO_Report();
	private serviceTypeItem servType = new DAO_typeItem();
    public reportItem() {
	    initComponents();
	    printButton.setVisible(false);
	    cancelButtonMain.setVisible(false);
	    filterPanel.setVisible(false);
	    hideFilterItem();
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                dataPanel = new javax.swing.JPanel();
                titleLabel2 = new javax.swing.JLabel();
                panelReport = new javax.swing.JPanel();
                printButton = new javax.swing.JButton();
                cancelButtonMain = new javax.swing.JButton();
                filterPanel = new javax.swing.JPanel();
                panelFilterItem = new javax.swing.JPanel();
                listFilter = new javax.swing.JComboBox<>();
                titleLabel3 = new javax.swing.JLabel();
                filter = new javax.swing.JPanel();
                dummyPanel = new javax.swing.JPanel();
                unitFilter = new javax.swing.JPanel();
                unitItem = new javax.swing.JComboBox<>();
                typeFilter = new javax.swing.JPanel();
                typeItem = new javax.swing.JComboBox<>();
                priceFilter = new javax.swing.JPanel();
                price2 = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                price1 = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                stockFilter = new javax.swing.JPanel();
                stock1 = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                stock2 = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                panelViewReport = new javax.swing.JPanel();

                setLayout(new java.awt.CardLayout());

                mainPanel.setLayout(new java.awt.CardLayout());

                dataPanel.setBackground(new java.awt.Color(255, 255, 255));
                dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                titleLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                titleLabel2.setText("Laporan Barang");
                dataPanel.add(titleLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, 54));

                printButton.setBackground(new java.awt.Color(102, 102, 255));
                printButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                printButton.setForeground(new java.awt.Color(255, 255, 255));
                printButton.setText("Print");
                printButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                printButtonActionPerformed(evt);
                        }
                });

                cancelButtonMain.setBackground(new java.awt.Color(255, 0, 0));
                cancelButtonMain.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                cancelButtonMain.setForeground(new java.awt.Color(255, 255, 255));
                cancelButtonMain.setText("Batal");
                cancelButtonMain.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonMainActionPerformed(evt);
                        }
                });

                filterPanel.setLayout(new java.awt.CardLayout());

                listFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Filter laporan -", "Tampilkan semua", "Satuan Barang", "Stock", "Jenis Barang", "Harga" }));
                listFilter.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                listFilterActionPerformed(evt);
                        }
                });

                titleLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                titleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                titleLabel3.setText("Filter Barang");

                filter.setLayout(new java.awt.CardLayout());

                javax.swing.GroupLayout dummyPanelLayout = new javax.swing.GroupLayout(dummyPanel);
                dummyPanel.setLayout(dummyPanelLayout);
                dummyPanelLayout.setHorizontalGroup(
                        dummyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 216, Short.MAX_VALUE)
                );
                dummyPanelLayout.setVerticalGroup(
                        dummyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 382, Short.MAX_VALUE)
                );

                filter.add(dummyPanel, "card2");

                unitItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Satuan -", "Kilogram", "Liter", "Gram", "Bungkus", "Pack", "Buah", "Sachet", "Dos", "Roll", "Packets", "Carton", "Pack of", "Piece", "Box\t", "Botol", "Literan (ltr)" }));
                unitItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                javax.swing.GroupLayout unitFilterLayout = new javax.swing.GroupLayout(unitFilter);
                unitFilter.setLayout(unitFilterLayout);
                unitFilterLayout.setHorizontalGroup(
                        unitFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(unitFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(unitItem, 0, 192, Short.MAX_VALUE)
                                .addContainerGap())
                );
                unitFilterLayout.setVerticalGroup(
                        unitFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(unitFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(unitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(333, Short.MAX_VALUE))
                );

                filter.add(unitFilter, "card2");

                typeItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jenis Barang -" }));

                javax.swing.GroupLayout typeFilterLayout = new javax.swing.GroupLayout(typeFilter);
                typeFilter.setLayout(typeFilterLayout);
                typeFilterLayout.setHorizontalGroup(
                        typeFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(typeFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(typeItem, 0, 192, Short.MAX_VALUE)
                                .addContainerGap())
                );
                typeFilterLayout.setVerticalGroup(
                        typeFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(typeFilterLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(typeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(311, Short.MAX_VALUE))
                );

                filter.add(typeFilter, "card2");

                price2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jLabel3.setText("Sampai dengan");

                price1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jLabel4.setText("Rentang Harga");

                javax.swing.GroupLayout priceFilterLayout = new javax.swing.GroupLayout(priceFilter);
                priceFilter.setLayout(priceFilterLayout);
                priceFilterLayout.setHorizontalGroup(
                        priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(priceFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(price1)
                                        .addComponent(price2)
                                        .addGroup(priceFilterLayout.createSequentialGroup()
                                                .addGroup(priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3))
                                                .addGap(0, 99, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                priceFilterLayout.setVerticalGroup(
                        priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(priceFilterLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(223, Short.MAX_VALUE))
                );

                filter.add(priceFilter, "card2");

                stock1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jLabel1.setText("Rentang Stock");

                stock2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jLabel2.setText("Sampai dengan");

                javax.swing.GroupLayout stockFilterLayout = new javax.swing.GroupLayout(stockFilter);
                stockFilter.setLayout(stockFilterLayout);
                stockFilterLayout.setHorizontalGroup(
                        stockFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(stockFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(stockFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stock1)
                                        .addComponent(stock2)
                                        .addGroup(stockFilterLayout.createSequentialGroup()
                                                .addGroup(stockFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(0, 99, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                stockFilterLayout.setVerticalGroup(
                        stockFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(stockFilterLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(223, Short.MAX_VALUE))
                );

                filter.add(stockFilter, "card2");

                javax.swing.GroupLayout panelFilterItemLayout = new javax.swing.GroupLayout(panelFilterItem);
                panelFilterItem.setLayout(panelFilterItemLayout);
                panelFilterItemLayout.setHorizontalGroup(
                        panelFilterItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFilterItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelFilterItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(listFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelFilterItemLayout.createSequentialGroup()
                                                .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addComponent(filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                panelFilterItemLayout.setVerticalGroup(
                        panelFilterItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFilterItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(listFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
                panelReport.setLayout(panelReportLayout);
                panelReportLayout.setHorizontalGroup(
                        panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelReportLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReportLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(panelFilterItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cancelButtonMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(printButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                );
                panelReportLayout.setVerticalGroup(
                        panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelReportLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(panelFilterItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                                .addGap(46, 46, 46)
                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButtonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                );

                dataPanel.add(panelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 770));

                panelViewReport.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout panelViewReportLayout = new javax.swing.GroupLayout(panelViewReport);
                panelViewReport.setLayout(panelViewReportLayout);
                panelViewReportLayout.setHorizontalGroup(
                        panelViewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 530, Short.MAX_VALUE)
                );
                panelViewReportLayout.setVerticalGroup(
                        panelViewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
                );

                dataPanel.add(panelViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 530, 740));

                mainPanel.add(dataPanel, "card2");

                add(mainPanel, "card2");
        }// </editor-fold>//GEN-END:initComponents

        private void cancelButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonMainActionPerformed
               panelDisplay();
        }//GEN-LAST:event_cancelButtonMainActionPerformed

        private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
		buttonReportItem();
		
        }//GEN-LAST:event_printButtonActionPerformed

        private void selectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemActionPerformed

		
        }//GEN-LAST:event_selectItemActionPerformed

    private void priceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceItemActionPerformed

        private void listFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFilterActionPerformed
                reportItem();
        }//GEN-LAST:event_listFilterActionPerformed

 private void panelDisplay(){
	
	mainPanel.removeAll();
	mainPanel.add(new reportItem());
        mainPanel.repaint();
        mainPanel.revalidate();
}



        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton cancelButtonMain;
        private javax.swing.JPanel dataPanel;
        private javax.swing.JPanel dummyPanel;
        private javax.swing.JPanel filter;
        private javax.swing.JPanel filterPanel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JComboBox<String> listFilter;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JPanel panelFilterItem;
        private javax.swing.JPanel panelReport;
        private javax.swing.JPanel panelViewReport;
        private javax.swing.JTextField price1;
        private javax.swing.JTextField price2;
        private javax.swing.JPanel priceFilter;
        private javax.swing.JButton printButton;
        private javax.swing.JTextField stock1;
        private javax.swing.JTextField stock2;
        private javax.swing.JPanel stockFilter;
        private javax.swing.JLabel titleLabel2;
        private javax.swing.JLabel titleLabel3;
        private javax.swing.JPanel typeFilter;
        private javax.swing.JComboBox<String> typeItem;
        private javax.swing.JPanel unitFilter;
        private javax.swing.JComboBox<String> unitItem;
        // End of variables declaration//GEN-END:variables

	
	
	
	
	private void printReportAll(){
		panelViewReport.removeAll();
		reportService.reportItemPanel(panelViewReport);
	}
	
	private void printReportUnit(){
		panelViewReport.removeAll();
		String no = unitItem.getSelectedItem().toString();
		reportService.reportItemFilterUnit(no,panelViewReport);
	}
	private void printReportType(){
		panelViewReport.removeAll();
		String no = typeItem.getSelectedItem().toString();
		reportService.reportItemFilterType(no,panelViewReport);
	}
	
	private void printReportStock(){
		panelViewReport.removeAll();
		int stock1 = Integer.parseInt(this.stock1.getText()) ;
		int stock2 = Integer.parseInt(this.stock2.getText()) ;
	
		reportService.reportItemFilterStock(stock1,stock2,panelViewReport);
	}
	
	private void printReportPrice(){
		panelViewReport.removeAll();
		int price1 = Integer.parseInt(this.price1.getText()) ;
		int price2 = Integer.parseInt(this.price2.getText()) ;
	
		reportService.reportItemFilterPrice(price1,price2,panelViewReport);
	}
	
	
	private void reportItem(){
		filterPanel.setVisible(true);
		if (listFilter.getSelectedIndex()==0) {
			hideFilterItem();
			disableButton();
		}else if (listFilter.getSelectedIndex()==1) {
			hideFilterItem();
			enableButton();
		}else if (listFilter.getSelectedIndex()==2) {
			hideFilterItem();
			enableButton();
			unitFilter.setVisible(true);
		}else if (listFilter.getSelectedIndex()==3) {
			hideFilterItem();
			enableButton();
			stockFilter.setVisible(true);
		}else if (listFilter.getSelectedIndex()==4) { 
			hideFilterItem();
			enableButton();
			typeList();
			typeFilter.setVisible(true);
		}else if (listFilter.getSelectedIndex()==5) {
			hideFilterItem();
			enableButton();
			priceFilter.setVisible(true);
		}
	}
	
	private void buttonReportItem(){
		if (listFilter.getSelectedIndex()==1) {
			printReportAll();
		}else if (listFilter.getSelectedIndex()==2) {
			printReportUnit();
		}else if (listFilter.getSelectedIndex()==3) {
			String stockValid1=stock1.getText();
			String stockValid2=stock2.getText();
			if (stockValid1.equals("") | (stockValid2.equals(""))) {
				JOptionPane.showMessageDialog(null, "Masukan rentang stock");
			}else {
				printReportStock();
			}
		}else if (listFilter.getSelectedIndex()==4) {
			printReportType();
		}else if (listFilter.getSelectedIndex()==5) {
			String priceValid1=price1.getText();
			String priceValid2=price1.getText();
			if (priceValid1.equals("") | (priceValid2.equals(""))) {
				JOptionPane.showMessageDialog(null, "Masukan rentang stock");
			}else {
				printReportPrice();
	}
		}
	}
	
	private void hideFilterItem(){
		dummyPanel.setVisible(false);
		typeFilter.setVisible(false);
		unitFilter.setVisible(false);
		priceFilter.setVisible(false);
		stockFilter.setVisible(false);
	}
	
	private void disableButton(){
		printButton.setVisible(false);
		cancelButtonMain.setVisible(false);
	}
	
	private void enableButton(){
		printButton.setVisible(true);
		cancelButtonMain.setVisible(true);
	}
	
	private void typeList(){
		servType.getDataComboBox();
		List<modelTypeItem> typeList = servType.getCarts();
		for (modelTypeItem type : typeList) {
		typeItem.addItem( type.getNameType());
	}
	}
}



