package edu.unindra.kkp_kelompok4.report;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import edu.unindra.kkp_kelompok4.Services.serviceEmployee;
import edu.unindra.kkp_kelompok4.Services.serviceReport;
import edu.unindra.kkp_kelompok4.dao.DAO_Employee;
import edu.unindra.kkp_kelompok4.dao.DAO_Report;
import edu.unindra.kkp_kelompok4.model.modelEmployee;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author ripal
 */
public class reportPerformanceCashier extends javax.swing.JPanel {
	private serviceEmployee servEmployee = new DAO_Employee();
	private serviceReport reportService = new DAO_Report();
	String employeeName;
    public reportPerformanceCashier(String employeeName) {
	    this.employeeName=employeeName;
	    initComponents();
	
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                dataPanel = new javax.swing.JPanel();
                panelViewReport = new javax.swing.JPanel();
                printButton = new javax.swing.JButton();
                cancelButtonMain = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setLayout(new java.awt.CardLayout());

                mainPanel.setLayout(new java.awt.CardLayout());

                dataPanel.setBackground(new java.awt.Color(255, 255, 255));
                dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                panelViewReport.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout panelViewReportLayout = new javax.swing.GroupLayout(panelViewReport);
                panelViewReport.setLayout(panelViewReportLayout);
                panelViewReportLayout.setHorizontalGroup(
                        panelViewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 780, Short.MAX_VALUE)
                );
                panelViewReportLayout.setVerticalGroup(
                        panelViewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
                );

                dataPanel.add(panelViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 740));

                printButton.setBackground(new java.awt.Color(102, 102, 255));
                printButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                printButton.setForeground(new java.awt.Color(255, 255, 255));
                printButton.setText("Print");
                printButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                printButtonActionPerformed(evt);
                        }
                });
                dataPanel.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 213, 37));

                cancelButtonMain.setBackground(new java.awt.Color(255, 0, 0));
                cancelButtonMain.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                cancelButtonMain.setForeground(new java.awt.Color(255, 255, 255));
                cancelButtonMain.setText("Batal");
                cancelButtonMain.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonMainActionPerformed(evt);
                        }
                });
                dataPanel.add(cancelButtonMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 213, 37));

                jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                jLabel1.setText("Laporan Harian Kasir");
                dataPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

                mainPanel.add(dataPanel, "card2");

                add(mainPanel, "card2");
        }// </editor-fold>//GEN-END:initComponents

        private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
		printReportAll();
		
        }//GEN-LAST:event_printButtonActionPerformed

        private void selectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemActionPerformed

		
        }//GEN-LAST:event_selectItemActionPerformed

    private void priceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceItemActionPerformed

        private void cancelButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonMainActionPerformed
                panelDisplay();
        }//GEN-LAST:event_cancelButtonMainActionPerformed

 private void panelDisplay(){
	
	mainPanel.removeAll();
	mainPanel.add(new reportPerformanceCashier(employeeName));
        mainPanel.repaint();
        mainPanel.revalidate();
}



        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton cancelButtonMain;
        private javax.swing.JPanel dataPanel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JPanel panelViewReport;
        private javax.swing.JButton printButton;
        // End of variables declaration//GEN-END:variables

	
	
	
	
	private void printReportAll(){
		Locale locale = new Locale("id", "ID");
		java.util.Date orderDateAutomatic = new java.util.Date();
		java.text.SimpleDateFormat dateOrder = new java.text.SimpleDateFormat("dd MMMM yyyy",locale);
		String dateReport = (dateOrder.format(orderDateAutomatic));
		
		panelViewReport.removeAll();
		reportService.reportPerformanceCashier(employeeName,dateReport,panelViewReport);
	}
}



