/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.homePage;

import AppPackage.AnimationClass;

/**
 *
 * @author ripal
 */
public class homePage extends javax.swing.JPanel {

	
	public homePage() {
		initComponents();
		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                cartLabel = new javax.swing.JLabel();
                labelMinimarket = new javax.swing.JLabel();
                picture3 = new javax.swing.JLabel();
                picture2 = new javax.swing.JLabel();
                picture1 = new javax.swing.JLabel();
                minimarketLabel = new javax.swing.JLabel();

                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                mainPanel.setBackground(new java.awt.Color(255, 255, 255));
                mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                cartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homePage/icons8_shopping_cart_100px_4.png"))); // NOI18N
                mainPanel.add(cartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

                labelMinimarket.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                labelMinimarket.setForeground(new java.awt.Color(153, 153, 255));
                labelMinimarket.setText("Barang lengkap harga bersahabat ya di UD YANTI");
                mainPanel.add(labelMinimarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 510, -1));

                picture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homePage/cherry-sale-1.png"))); // NOI18N
                mainPanel.add(picture3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

                picture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homePage/clip-1061.png"))); // NOI18N
                mainPanel.add(picture2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

                picture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homePage/ikigai-girl-in-a-grocery-store-with-a-cart-at-the-vegetable-section.png"))); // NOI18N
                mainPanel.add(picture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

                minimarketLabel.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                minimarketLabel.setForeground(new java.awt.Color(204, 204, 255));
                minimarketLabel.setText("UD YANTI");
                mainPanel.add(minimarketLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 330, -1));

                add(mainPanel);
        }// </editor-fold>//GEN-END:initComponents

	


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel cartLabel;
        private javax.swing.JLabel labelMinimarket;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JLabel minimarketLabel;
        private javax.swing.JLabel picture1;
        private javax.swing.JLabel picture2;
        private javax.swing.JLabel picture3;
        // End of variables declaration//GEN-END:variables
}
