/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.accountSetting;

import edu.unindra.kkp_kelompok4.Services.serviceAccountSetting;
import edu.unindra.kkp_kelompok4.dao.DAO_AccountSetting;
import edu.unindra.kkp_kelompok4.login.encryptLogin;
import edu.unindra.kkp_kelompok4.model.modelAccountSetting;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ripal
 */
public class accountSetting extends javax.swing.JPanel {

	modelAccountSetting account = new modelAccountSetting();
	serviceAccountSetting accountSetting = new DAO_AccountSetting();
	public accountSetting(String idEmployee){
		initComponents();
		account.setIdEmployee(idEmployee);
		accountInfo();
		jtNameEmployee1.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                genderGroup = new javax.swing.ButtonGroup();
                mainPanel = new javax.swing.JPanel();
                accountInfoPanel = new javax.swing.JPanel();
                password7 = new javax.swing.JLabel();
                choosePic1 = new javax.swing.JLabel();
                securitySetting = new javax.swing.JLabel();
                profileSettingButton = new javax.swing.JLabel();
                dataPanel1 = new javax.swing.JPanel();
                labelEmployeeId = new javax.swing.JLabel();
                labelEmployeeName = new javax.swing.JLabel();
                labelEmail = new javax.swing.JLabel();
                labelRole = new javax.swing.JLabel();
                labelDateAndPlaceOfBirth = new javax.swing.JLabel();
                labelAddress = new javax.swing.JLabel();
                fillEmployeeId = new javax.swing.JLabel();
                fillEmployeeName = new javax.swing.JLabel();
                fillDateAndPlaceOfBirth = new javax.swing.JLabel();
                fillEmail = new javax.swing.JLabel();
                fillRole = new javax.swing.JLabel();
                fillAddress = new javax.swing.JLabel();
                labelPin = new javax.swing.JLabel();
                fillPin = new javax.swing.JLabel();
                labelGender = new javax.swing.JLabel();
                fieldGender = new javax.swing.JLabel();
                phoneNumberLabel = new javax.swing.JLabel();
                fillPhoneNumber = new javax.swing.JLabel();
                fillPassword = new javax.swing.JLabel();
                labelPassword = new javax.swing.JLabel();
                securitySetting2 = new javax.swing.JPanel();
                employeeId1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                changePasswordButton = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                passwordInformation = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                pinInformation = new javax.swing.JLabel();
                changePinButton = new javax.swing.JLabel();
                profileSetting = new javax.swing.JPanel();
                dataPanel2 = new javax.swing.JPanel();
                employeeNamePanel1 = new javax.swing.JPanel();
                iconName1 = new javax.swing.JLabel();
                jtNameEmployee1 = new javax.swing.JTextField();
                employeeName3 = new javax.swing.JLabel();
                Gender = new javax.swing.JLabel();
                female = new javax.swing.JRadioButton();
                male = new javax.swing.JRadioButton();
                placeOfBirth = new javax.swing.JLabel();
                placeOfBirthPanel = new javax.swing.JPanel();
                iconPob = new javax.swing.JLabel();
                jtPlaceOfBirth = new javax.swing.JTextField();
                email = new javax.swing.JLabel();
                emailPanel = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jtEmail = new javax.swing.JTextField();
                jtGmail = new javax.swing.JTextField();
                dateOfBirth = new javax.swing.JLabel();
                dateOfBirthField = new com.toedter.calendar.JDateChooser();
                address = new javax.swing.JLabel();
                jScrollPane4 = new javax.swing.JScrollPane();
                tfAddress = new javax.swing.JTextArea();
                jButton3 = new javax.swing.JButton();
                cancelButton = new javax.swing.JButton();
                phoneNumber = new javax.swing.JLabel();
                phoneNumberPanel = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jtPhoneNumber = new javax.swing.JTextField();
                employeeId2 = new javax.swing.JLabel();
                choosePic2 = new javax.swing.JLabel();
                passwordSetting = new javax.swing.JPanel();
                dataPanel3 = new javax.swing.JPanel();
                PasswordPanel3 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                oldPassword = new javax.swing.JPasswordField();
                password4 = new javax.swing.JLabel();
                password5 = new javax.swing.JLabel();
                PasswordPanel4 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                newPassword = new javax.swing.JPasswordField();
                password6 = new javax.swing.JLabel();
                PasswordPanel5 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                confirmationNewPassword = new javax.swing.JPasswordField();
                employeeId3 = new javax.swing.JLabel();
                savePasswordChange = new javax.swing.JButton();
                cancelButtonPasswordChange = new javax.swing.JButton();
                pinSetting = new javax.swing.JPanel();
                dataPanel4 = new javax.swing.JPanel();
                PasswordPanel6 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                oldPin = new javax.swing.JPasswordField();
                password8 = new javax.swing.JLabel();
                password9 = new javax.swing.JLabel();
                PasswordPanel7 = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();
                newPin = new javax.swing.JPasswordField();
                password10 = new javax.swing.JLabel();
                PasswordPanel8 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                confirmationNewPin = new javax.swing.JPasswordField();
                employeeId4 = new javax.swing.JLabel();
                savePinChange = new javax.swing.JButton();
                cancelButtonPinChange = new javax.swing.JButton();

                setLayout(new java.awt.CardLayout());

                mainPanel.setLayout(new java.awt.CardLayout());

                password7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
                password7.setText("Informasi Akun");

                choosePic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                choosePic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/HomeApp/icons8_User_Default_200px.png"))); // NOI18N

                securitySetting.setBackground(new java.awt.Color(255, 51, 51));
                securitySetting.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                securitySetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_security_configuration_35px.png"))); // NOI18N
                securitySetting.setText("Pengaturan Keamanan");
                securitySetting.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                securitySettingMouseClicked(evt);
                        }
                });

                profileSettingButton.setBackground(new java.awt.Color(51, 255, 51));
                profileSettingButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                profileSettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_admin_settings_male_35px.png"))); // NOI18N
                profileSettingButton.setText("Pengaturan Profile");
                profileSettingButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                profileSettingButtonMouseClicked(evt);
                        }
                });

                labelEmployeeId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelEmployeeId.setText("ID Karyawan");

                labelEmployeeName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelEmployeeName.setText("Nama Karyawan");

                labelEmail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelEmail.setText("Email");

                labelRole.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelRole.setText("Jabatan");

                labelDateAndPlaceOfBirth.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelDateAndPlaceOfBirth.setText("Tempat, Tanggal Lahir");

                labelAddress.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelAddress.setText("Alamat");

                fillEmployeeId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillEmployeeId.setText(": ID Karyawan");

                fillEmployeeName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillEmployeeName.setText(": Nama Karyawan");

                fillDateAndPlaceOfBirth.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillDateAndPlaceOfBirth.setText(": Tempat, Tanggal lahir");

                fillEmail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillEmail.setText(": Email");

                fillRole.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillRole.setText(": Jabatan");

                fillAddress.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                fillAddress.setText(": Alamat");
                fillAddress.setVerticalAlignment(javax.swing.SwingConstants.TOP);

                labelPin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelPin.setText("PIN");

                fillPin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillPin.setText(": Pin Belum diatur");

                labelGender.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelGender.setText("Jenis Kelamin");

                fieldGender.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fieldGender.setText(": Jenis Kelamin");

                phoneNumberLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                phoneNumberLabel.setText("No HP");

                fillPhoneNumber.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillPhoneNumber.setText(": Email");

                fillPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                fillPassword.setText(": Password Belum diatur");

                labelPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                labelPassword.setText("Password");

                javax.swing.GroupLayout dataPanel1Layout = new javax.swing.GroupLayout(dataPanel1);
                dataPanel1.setLayout(dataPanel1Layout);
                dataPanel1Layout.setHorizontalGroup(
                        dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel1Layout.createSequentialGroup()
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelEmployeeId)
                                                        .addComponent(labelEmployeeName)
                                                        .addComponent(labelDateAndPlaceOfBirth)
                                                        .addComponent(labelEmail)
                                                        .addComponent(labelRole)
                                                        .addComponent(labelAddress)
                                                        .addComponent(labelPin)
                                                        .addComponent(labelGender)
                                                        .addComponent(phoneNumberLabel))
                                                .addGap(43, 43, 43))
                                        .addGroup(dataPanel1Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelPassword)
                                                .addGap(169, 169, 169)))
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel1Layout.createSequentialGroup()
                                                .addComponent(fillPassword)
                                                .addGap(129, 129, 129))
                                        .addGroup(dataPanel1Layout.createSequentialGroup()
                                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(dataPanel1Layout.createSequentialGroup()
                                                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(fillPhoneNumber)
                                                                        .addComponent(fieldGender)
                                                                        .addComponent(fillPin)
                                                                        .addComponent(fillRole)
                                                                        .addComponent(fillEmail)
                                                                        .addComponent(fillDateAndPlaceOfBirth)
                                                                        .addComponent(fillEmployeeName)
                                                                        .addComponent(fillEmployeeId))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(fillAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())))
                );
                dataPanel1Layout.setVerticalGroup(
                        dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelDateAndPlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillDateAndPlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fillPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillRole, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelPin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillPin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fillAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76))
                );

                javax.swing.GroupLayout accountInfoPanelLayout = new javax.swing.GroupLayout(accountInfoPanel);
                accountInfoPanel.setLayout(accountInfoPanelLayout);
                accountInfoPanelLayout.setHorizontalGroup(
                        accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(accountInfoPanelLayout.createSequentialGroup()
                                .addGroup(accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(accountInfoPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(password7, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(accountInfoPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(profileSettingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(securitySetting, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(accountInfoPanelLayout.createSequentialGroup()
                                                .addGap(242, 242, 242)
                                                .addComponent(choosePic1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(accountInfoPanelLayout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(dataPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(153, Short.MAX_VALUE))
                );
                accountInfoPanelLayout.setVerticalGroup(
                        accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(accountInfoPanelLayout.createSequentialGroup()
                                .addComponent(password7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(choosePic1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(dataPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(securitySetting)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profileSettingButton)
                                .addContainerGap(16, Short.MAX_VALUE))
                );

                mainPanel.add(accountInfoPanel, "card3");

                employeeId1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                employeeId1.setText("Pengaturan Keamanan");

                changePasswordButton.setBackground(new java.awt.Color(255, 255, 255));
                changePasswordButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                changePasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_lock_35px.png"))); // NOI18N
                changePasswordButton.setText("Ubah Password");
                changePasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                changePasswordButtonMouseClicked(evt);
                        }
                });

                jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel2.setBackground(new java.awt.Color(255, 255, 255));
                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Password");
                jLabel2.setPreferredSize(new java.awt.Dimension(340, 25));

                passwordInformation.setBackground(new java.awt.Color(255, 255, 255));
                passwordInformation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                passwordInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                passwordInformation.setText("Password masih dalam keadaan default");
                passwordInformation.setPreferredSize(new java.awt.Dimension(340, 25));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(passwordInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(14, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel4.setBackground(new java.awt.Color(255, 255, 255));
                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("PIN");
                jLabel4.setPreferredSize(new java.awt.Dimension(340, 25));

                pinInformation.setBackground(new java.awt.Color(255, 255, 255));
                pinInformation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                pinInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                pinInformation.setText("PIN masih dalam keadaan default");
                pinInformation.setPreferredSize(new java.awt.Dimension(340, 25));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(pinInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(14, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pinInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                changePinButton.setBackground(new java.awt.Color(255, 255, 255));
                changePinButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                changePinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_Password_35px_1.png"))); // NOI18N
                changePinButton.setText("Ubah PIN");
                changePinButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                changePinButtonMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(changePinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(131, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 32, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changePasswordButton)
                                .addGap(59, 59, 59)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(changePinButton))
                );

                javax.swing.GroupLayout securitySetting2Layout = new javax.swing.GroupLayout(securitySetting2);
                securitySetting2.setLayout(securitySetting2Layout);
                securitySetting2Layout.setHorizontalGroup(
                        securitySetting2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(securitySetting2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(securitySetting2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(employeeId1))
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                securitySetting2Layout.setVerticalGroup(
                        securitySetting2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(securitySetting2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(employeeId1)
                                .addGap(40, 40, 40)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE))
                );

                mainPanel.add(securitySetting2, "card2");

                employeeNamePanel1.setBackground(new java.awt.Color(255, 255, 255));
                employeeNamePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                employeeNamePanel1.setLayout(new javax.swing.BoxLayout(employeeNamePanel1, javax.swing.BoxLayout.LINE_AXIS));

                iconName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_registration_35px_2.png"))); // NOI18N
                iconName1.setPreferredSize(new java.awt.Dimension(45, 35));
                employeeNamePanel1.add(iconName1);

                jtNameEmployee1.setBorder(null);
                employeeNamePanel1.add(jtNameEmployee1);

                employeeName3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                employeeName3.setText("Nama Karyawan");

                Gender.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                Gender.setText("Jenis Kelamain");

                genderGroup.add(female);
                female.setText("Perempuan");

                genderGroup.add(male);
                male.setText("Laki-Laki");

                placeOfBirth.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                placeOfBirth.setText("Tempat Lahir");

                placeOfBirthPanel.setBackground(new java.awt.Color(255, 255, 255));
                placeOfBirthPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                placeOfBirthPanel.setLayout(new javax.swing.BoxLayout(placeOfBirthPanel, javax.swing.BoxLayout.LINE_AXIS));

                iconPob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_office_35px.png"))); // NOI18N
                iconPob.setPreferredSize(new java.awt.Dimension(45, 35));
                placeOfBirthPanel.add(iconPob);

                jtPlaceOfBirth.setBorder(null);
                placeOfBirthPanel.add(jtPlaceOfBirth);

                email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                email.setText("Email");

                emailPanel.setBackground(new java.awt.Color(255, 255, 255));
                emailPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                emailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setBackground(new java.awt.Color(255, 255, 255));
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_at_sign_35px.png"))); // NOI18N
                emailPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 3, -1, -1));

                jtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                jtEmail.setBorder(null);
                emailPanel.add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 1, 180, 37));

                jtGmail.setForeground(new java.awt.Color(102, 102, 102));
                jtGmail.setText("@gmail.com");
                jtGmail.setBorder(null);
                jtGmail.setPreferredSize(new java.awt.Dimension(2, 16));
                jtGmail.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jtGmailActionPerformed(evt);
                        }
                });
                emailPanel.add(jtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 1, 90, 37));

                dateOfBirth.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                dateOfBirth.setText("Tanggal Lahir");

                dateOfBirthField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                dateOfBirthField.setDateFormatString("dd MMMM yyyy");

                address.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                address.setText("Alamat");

                tfAddress.setColumns(20);
                tfAddress.setRows(5);
                tfAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jScrollPane4.setViewportView(tfAddress);

                jButton3.setBackground(new java.awt.Color(0, 0, 255));
                jButton3.setForeground(new java.awt.Color(255, 255, 255));
                jButton3.setText("Simpan");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                cancelButton.setBackground(new java.awt.Color(255, 0, 0));
                cancelButton.setForeground(new java.awt.Color(255, 255, 255));
                cancelButton.setText("Batal");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                phoneNumber.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                phoneNumber.setText("No HP");

                phoneNumberPanel.setBackground(new java.awt.Color(255, 255, 255));
                phoneNumberPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                phoneNumberPanel.setLayout(new javax.swing.BoxLayout(phoneNumberPanel, javax.swing.BoxLayout.LINE_AXIS));

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_phone_35px.png"))); // NOI18N
                phoneNumberPanel.add(jLabel6);

                jtPhoneNumber.setBorder(null);
                jtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jtPhoneNumberActionPerformed(evt);
                        }
                });
                phoneNumberPanel.add(jtPhoneNumber);

                javax.swing.GroupLayout dataPanel2Layout = new javax.swing.GroupLayout(dataPanel2);
                dataPanel2.setLayout(dataPanel2Layout);
                dataPanel2Layout.setHorizontalGroup(
                        dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(placeOfBirthPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(employeeName3, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Gender, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataPanel2Layout.createSequentialGroup()
                                                                .addComponent(male)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(female))
                                                        .addComponent(placeOfBirth, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dateOfBirth, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(employeeNamePanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(dateOfBirthField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanel2Layout.createSequentialGroup()
                                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(email))
                                                                .addGap(72, 72, 72))
                                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(phoneNumber)
                                                                        .addComponent(address)
                                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                                                        .addComponent(phoneNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addContainerGap())))))
                );
                dataPanel2Layout.setVerticalGroup(
                        dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                                .addGap(182, 182, 182)
                                                                .addComponent(placeOfBirthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                                .addComponent(employeeName3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(employeeNamePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(9, 9, 9)
                                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(male)
                                                                        .addComponent(female))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(placeOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(11, 11, 11)
                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(dateOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(47, 47, 47)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(dataPanel2Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(phoneNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(dataPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(cancelButton))
                                .addContainerGap(47, Short.MAX_VALUE))
                );

                employeeId2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                employeeId2.setText("Ubah Profile");

                choosePic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                choosePic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/HomeApp/icons8_User_Default_200px.png"))); // NOI18N
                choosePic2.setToolTipText("<html><p style=\"font-size: 18px; background-color: white; color: black;\">\n  Klik <span style=\"text-decoration: none;\">Foto</span> untuk ganti foto profil\n</p>\n");
                choosePic2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                choosePic2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                choosePic2MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout profileSettingLayout = new javax.swing.GroupLayout(profileSetting);
                profileSetting.setLayout(profileSettingLayout);
                profileSettingLayout.setHorizontalGroup(
                        profileSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profileSettingLayout.createSequentialGroup()
                                .addGroup(profileSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(profileSettingLayout.createSequentialGroup()
                                                .addGap(236, 236, 236)
                                                .addComponent(employeeId2))
                                        .addGroup(profileSettingLayout.createSequentialGroup()
                                                .addGap(282, 282, 282)
                                                .addComponent(choosePic2))
                                        .addGroup(profileSettingLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(dataPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                profileSettingLayout.setVerticalGroup(
                        profileSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profileSettingLayout.createSequentialGroup()
                                .addComponent(employeeId2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(choosePic2)
                                .addGap(22, 22, 22)
                                .addComponent(dataPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                );

                mainPanel.add(profileSetting, "card2");

                PasswordPanel3.setBackground(new java.awt.Color(255, 255, 255));
                PasswordPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                PasswordPanel3.setLayout(new javax.swing.BoxLayout(PasswordPanel3, javax.swing.BoxLayout.LINE_AXIS));

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_lock_35px.png"))); // NOI18N
                PasswordPanel3.add(jLabel7);

                oldPassword.setBorder(null);
                PasswordPanel3.add(oldPassword);

                password4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                password4.setText("Password Lama");

                password5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                password5.setText("Password Baru");

                PasswordPanel4.setBackground(new java.awt.Color(255, 255, 255));
                PasswordPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                PasswordPanel4.setLayout(new javax.swing.BoxLayout(PasswordPanel4, javax.swing.BoxLayout.LINE_AXIS));

                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_lock_35px.png"))); // NOI18N
                PasswordPanel4.add(jLabel8);

                newPassword.setBorder(null);
                PasswordPanel4.add(newPassword);

                password6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                password6.setText("Konfirmasi Password Baru");

                PasswordPanel5.setBackground(new java.awt.Color(255, 255, 255));
                PasswordPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                PasswordPanel5.setLayout(new javax.swing.BoxLayout(PasswordPanel5, javax.swing.BoxLayout.LINE_AXIS));

                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_lock_35px.png"))); // NOI18N
                PasswordPanel5.add(jLabel9);

                confirmationNewPassword.setBorder(null);
                PasswordPanel5.add(confirmationNewPassword);

                javax.swing.GroupLayout dataPanel3Layout = new javax.swing.GroupLayout(dataPanel3);
                dataPanel3.setLayout(dataPanel3Layout);
                dataPanel3Layout.setHorizontalGroup(
                        dataPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dataPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PasswordPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PasswordPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(dataPanel3Layout.createSequentialGroup()
                                                .addGroup(dataPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(password4)
                                                        .addComponent(password5)
                                                        .addComponent(password6))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                dataPanel3Layout.setVerticalGroup(
                        dataPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dataPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel3Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(PasswordPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(password4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel3Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(PasswordPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(password5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel3Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(PasswordPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(password6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
                );

                employeeId3.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                employeeId3.setText("Ubah Password");

                savePasswordChange.setBackground(new java.awt.Color(0, 0, 255));
                savePasswordChange.setForeground(new java.awt.Color(255, 255, 255));
                savePasswordChange.setText("Simpan");
                savePasswordChange.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                savePasswordChangeActionPerformed(evt);
                        }
                });

                cancelButtonPasswordChange.setBackground(new java.awt.Color(255, 0, 0));
                cancelButtonPasswordChange.setForeground(new java.awt.Color(255, 255, 255));
                cancelButtonPasswordChange.setText("Batal");
                cancelButtonPasswordChange.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonPasswordChangeActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout passwordSettingLayout = new javax.swing.GroupLayout(passwordSetting);
                passwordSetting.setLayout(passwordSettingLayout);
                passwordSettingLayout.setHorizontalGroup(
                        passwordSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwordSettingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(passwordSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dataPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(passwordSettingLayout.createSequentialGroup()
                                                .addGroup(passwordSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(passwordSettingLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(savePasswordChange)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cancelButtonPasswordChange, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(employeeId3))
                                                .addGap(0, 379, Short.MAX_VALUE))))
                );
                passwordSettingLayout.setVerticalGroup(
                        passwordSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwordSettingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(employeeId3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(passwordSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(savePasswordChange)
                                        .addComponent(cancelButtonPasswordChange))
                                .addContainerGap(73, Short.MAX_VALUE))
                );

                mainPanel.add(passwordSetting, "card2");

                PasswordPanel6.setBackground(new java.awt.Color(255, 255, 255));
                PasswordPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                PasswordPanel6.setLayout(new javax.swing.BoxLayout(PasswordPanel6, javax.swing.BoxLayout.LINE_AXIS));

                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_lock_35px.png"))); // NOI18N
                PasswordPanel6.add(jLabel10);

                oldPin.setBorder(null);
                PasswordPanel6.add(oldPin);

                password8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                password8.setText("PIN Lama");

                password9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                password9.setText("PIN Baru");

                PasswordPanel7.setBackground(new java.awt.Color(255, 255, 255));
                PasswordPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                PasswordPanel7.setLayout(new javax.swing.BoxLayout(PasswordPanel7, javax.swing.BoxLayout.LINE_AXIS));

                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_lock_35px.png"))); // NOI18N
                PasswordPanel7.add(jLabel11);

                newPin.setBorder(null);
                newPin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                newPinActionPerformed(evt);
                        }
                });
                PasswordPanel7.add(newPin);

                password10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                password10.setText("Konfirmasi PIN Baru");

                PasswordPanel8.setBackground(new java.awt.Color(255, 255, 255));
                PasswordPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                PasswordPanel8.setLayout(new javax.swing.BoxLayout(PasswordPanel8, javax.swing.BoxLayout.LINE_AXIS));

                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_lock_35px.png"))); // NOI18N
                PasswordPanel8.add(jLabel12);

                confirmationNewPin.setBorder(null);
                PasswordPanel8.add(confirmationNewPin);

                javax.swing.GroupLayout dataPanel4Layout = new javax.swing.GroupLayout(dataPanel4);
                dataPanel4.setLayout(dataPanel4Layout);
                dataPanel4Layout.setHorizontalGroup(
                        dataPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dataPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PasswordPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PasswordPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(dataPanel4Layout.createSequentialGroup()
                                                .addGroup(dataPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(password8)
                                                        .addComponent(password9)
                                                        .addComponent(password10))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                dataPanel4Layout.setVerticalGroup(
                        dataPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dataPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel4Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(PasswordPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(password8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel4Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(PasswordPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(password9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanel4Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(PasswordPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(password10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
                );

                employeeId4.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                employeeId4.setText("Ubah PIN");

                savePinChange.setBackground(new java.awt.Color(0, 0, 255));
                savePinChange.setForeground(new java.awt.Color(255, 255, 255));
                savePinChange.setText("Simpan");
                savePinChange.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                savePinChangeActionPerformed(evt);
                        }
                });

                cancelButtonPinChange.setBackground(new java.awt.Color(255, 0, 0));
                cancelButtonPinChange.setForeground(new java.awt.Color(255, 255, 255));
                cancelButtonPinChange.setText("Batal");
                cancelButtonPinChange.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonPinChangeActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout pinSettingLayout = new javax.swing.GroupLayout(pinSetting);
                pinSetting.setLayout(pinSettingLayout);
                pinSettingLayout.setHorizontalGroup(
                        pinSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pinSettingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pinSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dataPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pinSettingLayout.createSequentialGroup()
                                                .addGroup(pinSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pinSettingLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(savePinChange)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cancelButtonPinChange, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(employeeId4))
                                                .addGap(0, 520, Short.MAX_VALUE))))
                );
                pinSettingLayout.setVerticalGroup(
                        pinSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pinSettingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(employeeId4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pinSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(savePinChange)
                                        .addComponent(cancelButtonPinChange))
                                .addContainerGap(73, Short.MAX_VALUE))
                );

                mainPanel.add(pinSetting, "card2");

                add(mainPanel, "card5");
        }// </editor-fold>//GEN-END:initComponents

        private void jtGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtGmailActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jtGmailActionPerformed

        private void profileSettingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileSettingButtonMouseClicked
		mainPanel.removeAll();
		mainPanel.repaint();
		mainPanel.revalidate();

		mainPanel.add(profileSetting);
		mainPanel.repaint();
		mainPanel.revalidate();
		
		editProfile();
        }//GEN-LAST:event_profileSettingButtonMouseClicked

        private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
              panelDisplay();
        }//GEN-LAST:event_cancelButtonActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              saveProfile();	
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPhoneNumberActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jtPhoneNumberActionPerformed

        private void choosePic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choosePic2MouseClicked
             changePicture();
        }//GEN-LAST:event_choosePic2MouseClicked

        private void securitySettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_securitySettingMouseClicked
               mainPanel.removeAll();
		mainPanel.repaint();
		mainPanel.revalidate();

		mainPanel.add(securitySetting2);
		mainPanel.repaint();
		mainPanel.revalidate();
		securityInformation();
        }//GEN-LAST:event_securitySettingMouseClicked

        private void changePasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordButtonMouseClicked
                mainPanel.removeAll();
		mainPanel.repaint();
		mainPanel.revalidate();

		mainPanel.add(passwordSetting);
		mainPanel.repaint();
		mainPanel.revalidate();
        }//GEN-LAST:event_changePasswordButtonMouseClicked

        private void savePasswordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePasswordChangeActionPerformed
                changePassword();
        }//GEN-LAST:event_savePasswordChangeActionPerformed

        private void cancelButtonPasswordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonPasswordChangeActionPerformed
                mainPanel.removeAll();
		mainPanel.repaint();
		mainPanel.revalidate();

		mainPanel.add(securitySetting2);
		mainPanel.repaint();
		mainPanel.revalidate();
        }//GEN-LAST:event_cancelButtonPasswordChangeActionPerformed

        private void savePinChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePinChangeActionPerformed
               changePin();
        }//GEN-LAST:event_savePinChangeActionPerformed

        private void cancelButtonPinChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonPinChangeActionPerformed
                mainPanel.removeAll();
		mainPanel.repaint();
		mainPanel.revalidate();

		mainPanel.add(securitySetting2);
		mainPanel.repaint();
		mainPanel.revalidate();
        }//GEN-LAST:event_cancelButtonPinChangeActionPerformed

        private void newPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPinActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_newPinActionPerformed

        private void changePinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePinButtonMouseClicked
                mainPanel.removeAll();
		mainPanel.repaint();
		mainPanel.revalidate();

		mainPanel.add(pinSetting);
		mainPanel.repaint();
		mainPanel.revalidate();
        }//GEN-LAST:event_changePinButtonMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel Gender;
        private javax.swing.JPanel PasswordPanel3;
        private javax.swing.JPanel PasswordPanel4;
        private javax.swing.JPanel PasswordPanel5;
        private javax.swing.JPanel PasswordPanel6;
        private javax.swing.JPanel PasswordPanel7;
        private javax.swing.JPanel PasswordPanel8;
        private javax.swing.JPanel accountInfoPanel;
        private javax.swing.JLabel address;
        private javax.swing.JButton cancelButton;
        private javax.swing.JButton cancelButtonPasswordChange;
        private javax.swing.JButton cancelButtonPinChange;
        private javax.swing.JLabel changePasswordButton;
        private javax.swing.JLabel changePinButton;
        private javax.swing.JLabel choosePic1;
        private javax.swing.JLabel choosePic2;
        private javax.swing.JPasswordField confirmationNewPassword;
        private javax.swing.JPasswordField confirmationNewPin;
        private javax.swing.JPanel dataPanel1;
        private javax.swing.JPanel dataPanel2;
        private javax.swing.JPanel dataPanel3;
        private javax.swing.JPanel dataPanel4;
        private javax.swing.JLabel dateOfBirth;
        private com.toedter.calendar.JDateChooser dateOfBirthField;
        private javax.swing.JLabel email;
        private javax.swing.JPanel emailPanel;
        private javax.swing.JLabel employeeId1;
        private javax.swing.JLabel employeeId2;
        private javax.swing.JLabel employeeId3;
        private javax.swing.JLabel employeeId4;
        private javax.swing.JLabel employeeName3;
        private javax.swing.JPanel employeeNamePanel1;
        private javax.swing.JRadioButton female;
        private javax.swing.JLabel fieldGender;
        private javax.swing.JLabel fillAddress;
        private javax.swing.JLabel fillDateAndPlaceOfBirth;
        private javax.swing.JLabel fillEmail;
        private javax.swing.JLabel fillEmployeeId;
        private javax.swing.JLabel fillEmployeeName;
        private javax.swing.JLabel fillPassword;
        private javax.swing.JLabel fillPhoneNumber;
        private javax.swing.JLabel fillPin;
        private javax.swing.JLabel fillRole;
        private javax.swing.ButtonGroup genderGroup;
        private javax.swing.JLabel iconName1;
        private javax.swing.JLabel iconPob;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JTextField jtEmail;
        private javax.swing.JTextField jtGmail;
        private javax.swing.JTextField jtNameEmployee1;
        private javax.swing.JTextField jtPhoneNumber;
        private javax.swing.JTextField jtPlaceOfBirth;
        private javax.swing.JLabel labelAddress;
        private javax.swing.JLabel labelDateAndPlaceOfBirth;
        private javax.swing.JLabel labelEmail;
        private javax.swing.JLabel labelEmployeeId;
        private javax.swing.JLabel labelEmployeeName;
        private javax.swing.JLabel labelGender;
        private javax.swing.JLabel labelPassword;
        private javax.swing.JLabel labelPin;
        private javax.swing.JLabel labelRole;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JRadioButton male;
        private javax.swing.JPasswordField newPassword;
        private javax.swing.JPasswordField newPin;
        private javax.swing.JPasswordField oldPassword;
        private javax.swing.JPasswordField oldPin;
        private javax.swing.JLabel password10;
        private javax.swing.JLabel password4;
        private javax.swing.JLabel password5;
        private javax.swing.JLabel password6;
        private javax.swing.JLabel password7;
        private javax.swing.JLabel password8;
        private javax.swing.JLabel password9;
        private javax.swing.JLabel passwordInformation;
        private javax.swing.JPanel passwordSetting;
        private javax.swing.JLabel phoneNumber;
        private javax.swing.JLabel phoneNumberLabel;
        private javax.swing.JPanel phoneNumberPanel;
        private javax.swing.JLabel pinInformation;
        private javax.swing.JPanel pinSetting;
        private javax.swing.JLabel placeOfBirth;
        private javax.swing.JPanel placeOfBirthPanel;
        private javax.swing.JPanel profileSetting;
        private javax.swing.JLabel profileSettingButton;
        private javax.swing.JButton savePasswordChange;
        private javax.swing.JButton savePinChange;
        private javax.swing.JLabel securitySetting;
        private javax.swing.JPanel securitySetting2;
        private javax.swing.JTextArea tfAddress;
        // End of variables declaration//GEN-END:variables

private void accountInfo() {
	accountInformation();
	fillEmployeeId.setText(account.getIdEmployee());
	fillEmployeeName.setText(account.getEmployeeName());
	fieldGender.setText(account.getGender());

	java.util.Date dob = account.getDateOfBirth();
	java.sql.Date dateOfBirthConvert = new java.sql.Date(dob.getTime());

	// Mengatur format tanggal yang diinginkan
	SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy", Locale.getDefault());
	String dobString = dateFormat.format(dob); // Mengubah objek Date menjadi String dengan format tertentu

	fillDateAndPlaceOfBirth.setText(account.getPlaceOfBirth() + " - " + dobString);
	fillEmail.setText(account.getEmail());
	fillPhoneNumber.setText(account.getPhoneNumber());
	fillRole.setText(account.getRole());

	String checkPin = account.getPin();
	if (checkPin.equals("827ccb0eea8a706c4c34a16891f84e7b")) {
	    fillPin.setText("PIN Default, Segera ganti pin");
	    fillPin.setForeground(new java.awt.Color(255, 51, 51));
	} else {
	    fillPin.setText("Pin sudah diatur");
	    fillPin.setForeground(new java.awt.Color(0, 0, 0));
	}
	
	String password = account.getPassword();
	if (password.equals("21232f297a57a5a743894a0e4a801fc3")) {
	    fillPassword.setText("Password Default, Segera ganti Password");
	    fillPassword.setForeground(new java.awt.Color(255, 51, 51));
	} else {
	    fillPassword.setText("Password sudah diatur");
	    fillPassword.setForeground(new java.awt.Color(0, 0, 0));
	}
	fillAddress.setText(account.getAddress());
    }
private void securityInformation(){
	accountSetting.displayAccount(account);
	String checkPin = account.getPin();
	if (checkPin.equals("827ccb0eea8a706c4c34a16891f84e7b")) {
	    pinInformation.setText("PIN masih dalam keadaan default");
	    pinInformation.setForeground(new java.awt.Color(255, 51, 51));
	} else {
	    pinInformation.setText("Pin sudah diatur");
	    pinInformation.setForeground(new java.awt.Color(0, 0, 0));
	}
	
	String password = account.getPassword();
	if (password.equals("21232f297a57a5a743894a0e4a801fc3")) {
	    passwordInformation.setText("Password masih dalam keadaan default");
	    passwordInformation.setForeground(new java.awt.Color(255, 51, 51));
	} else {
	    passwordInformation.setText("Password sudah diatur");
	    passwordInformation.setForeground(new java.awt.Color(0, 0, 0));
	}
}

private void changePicture() {
    JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
    fileChooser.setFileFilter(imageFilter);
    int result = fileChooser.showOpenDialog(null);

    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();

        try {
            if (selectedFile != null) {
                ImageIcon img = new ImageIcon(selectedFile.getPath());

                // Get the original image dimensions
                int pictureWidth = img.getIconWidth();
                int pictureHeight = img.getIconHeight();

                // Mengubah ukuran gambar sesuai kebutuhan
                int labelWidth = 230;
                int labelHeight = 150;
                double scaleX = (double) labelWidth / (double) pictureWidth;
                double scaleY = (double) labelHeight / (double) pictureHeight;
                double scale = Math.min(scaleX, scaleY);

                // Scale the image
                int scaledWidth = (int) (scale * pictureWidth);
                int scaledHeight = (int) (scale * pictureHeight);
                Image scaledPicture = img.getImage().getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);

                BufferedImage bufferedImage = new BufferedImage(scaledWidth, scaledHeight, BufferedImage.TYPE_INT_RGB);

                // Draw the scaled picture onto the BufferedImage
                Graphics2D g2d = bufferedImage.createGraphics();
                g2d.drawImage(scaledPicture, 0, 0, null);
                g2d.dispose();

                // Write the BufferedImage to a ByteArrayOutputStream
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(bufferedImage, "JPEG", baos);
                byte[] picture = baos.toByteArray();
                baos.close();

                account.setPictures(picture);
                choosePic2.setIcon(new ImageIcon(scaledPicture));
            } else {
		byte[]picture=account.getPictures();
                ImageIcon img = new ImageIcon(picture);
                choosePic2.setIcon(img);
                account.setPictures(picture);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}


private void accountInformation(){
	accountSetting.displayAccount(account);
	
	byte[]picture=account.getPictures();
	
	try {
		if (picture != null && picture.length > 0) {
//		    byte[] profilePic = picture.getBytes(1, (int) picture.length());
		    ImageIcon img = new ImageIcon(picture);
		    // Mengubah ukuran gambar sesuai kebutuhan
		    int labelWidth = 230;
		    int labelHeight = 150;
		    int pictureWidth = img.getIconWidth();
		    int pictureHeight = img.getIconHeight();
		    double scaleX = (double) labelWidth / (double) pictureWidth;
		    double scaleY = (double) labelHeight / (double) pictureHeight;
		    double scale = Math.min(scaleX, scaleY);
		    Image scaledPicture = img.getImage().getScaledInstance((int) (scale * pictureWidth), (int) (scale * pictureHeight), Image.SCALE_SMOOTH);

		    choosePic1.setIcon(new ImageIcon(scaledPicture));
		    choosePic2.setIcon(new ImageIcon(scaledPicture));
		} else {
		    // Mengatur ikon asli atau placeholder jika Blob picture kosong
		     choosePic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/HomeApp/icons8_User_Default_200px.png"))); // NOI18N
		     choosePic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/HomeApp/icons8_User_Default_200px.png")));
		}
	        } catch (Exception e) {
		    e.printStackTrace();
}
}

private void editProfile(){
	accountInformation();

	jtNameEmployee1.setText(account.getEmployeeName());
	String gender = account.getGender();
		if (gender.equals("Laki-Laki")) {
		    male.setSelected(true);
		} else if (gender.equals("Perempuan")) {
		    female.setSelected(true);
		}
	jtPlaceOfBirth.setText(account.getPlaceOfBirth());
	java.util.Date dob = account.getDateOfBirth();
	java.sql.Date dateOfBirthConvert = new java.sql.Date(dob.getTime());

	// Mengatur format tanggal yang diinginkan
//	SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy", Locale.getDefault());
//	String dobString = dateFormat.format(dob); // 

	dateOfBirthField.setDate(dob);
	String email = account.getEmail();
		if (email.length() > 10) {
		    email = email.substring(0, email.length() - 10);
		}
	jtEmail.setText(email);
	tfAddress.setText(account.getAddress());
	jtPhoneNumber.setText(account.getPhoneNumber());
	

}


private void saveProfile() {
    modelAccountSetting accountRenew = new modelAccountSetting();
    String id = account.getIdEmployee();
    String name = jtNameEmployee1.getText();
    String gender = "";
    if (male.isSelected()) {
        gender = male.getText();
    } else if (female.isSelected()) {
        gender = female.getText();
    }
    String placeOfBirth = jtPlaceOfBirth.getText();
    java.util.Date dob = dateOfBirthField.getDate();
    java.sql.Date dateOfBirthConvert = new java.sql.Date(dob.getTime());
    String address = tfAddress.getText();
    String email = jtEmail.getText() + jtGmail.getText();
    String phoneNumberEmployee = jtPhoneNumber.getText();
    Icon pictures = choosePic2.getIcon();

    accountRenew.setIdEmployee(id);
    accountRenew.setEmployeeName(name);
    accountRenew.setGender(gender);
    accountRenew.setPlaceOfBirth(placeOfBirth);
    accountRenew.setDateOfBirth(dateOfBirthConvert);
    accountRenew.setAddress(address);
    accountRenew.setEmail(email);
    accountRenew.setPhoneNumber(phoneNumberEmployee);

    if (pictures instanceof ImageIcon) {
        ImageIcon imageIcon = (ImageIcon) pictures;
        Image image = imageIcon.getImage();

        BufferedImage bufferedImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = bufferedImage.createGraphics();
        g2d.drawImage(image, 0, 0, null);
        g2d.dispose();

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            ImageIO.write(bufferedImage, "JPEG", baos);
            byte[] picture = baos.toByteArray();
            accountRenew.setPictures(picture);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    accountSetting.profileSetting(accountRenew);
    
    panelDisplay();
    accountInfo();
}


private void changePassword() {
    accountSetting.displayAccount(account);
    String passwordOldCheck = account.getPassword();
    String oldPass = encryptLogin.getMD5(oldPassword.getText());
    String newPass = newPassword.getText();
    String newConfirmationPassword = confirmationNewPassword.getText();
    
    if (oldPass.equals(passwordOldCheck)) {
        if (newPass.equals(newConfirmationPassword)) {
            account.setPassword(encryptLogin.getMD5(newPass));
            accountSetting.passwordChange(account);
            panelDisplay();
            accountInfo();
        } else {
            JOptionPane.showMessageDialog(null, "Password Baru tidak sesuai");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Password tidak sesuai dengan yang terdaftar di database");
    }
}

private void changePin() {
    accountSetting.displayAccount(account);
    String pinOldCheck = account.getPin();
    String oldPins = encryptLogin.getMD5(oldPin.getText());
    String newPins = newPin.getText();
    String newConfirmationPins = confirmationNewPin.getText();
    
    if (oldPins.equals(pinOldCheck)) {
        if (newPins.equals(newConfirmationPins)) {
            account.setPin(encryptLogin.getMD5(newPins));
            accountSetting.pinChange(account);
            panelDisplay();
            accountInfo();
        } else {
            JOptionPane.showMessageDialog(null, "PIN Baru tidak sesuai");
        }
    } else {
        JOptionPane.showMessageDialog(null, "PIN tidak sesuai dengan yang terdaftar di database");
    }
}


private void panelDisplay(){
	  mainPanel.removeAll();
		mainPanel.repaint();
		mainPanel.revalidate();

		mainPanel.add(accountInfoPanel);
		mainPanel.repaint();
		mainPanel.revalidate();
}
}
