/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.unindra.kkp_kelompok4.transaction;


import edu.unindra.kkp_kelompok4.Services.serviceItem;
import edu.unindra.kkp_kelompok4.TableModel.tableModelItem;
import edu.unindra.kkp_kelompok4.dao.DAO_Items;
import edu.unindra.kkp_kelompok4.model.modelItem;
import java.util.List;

/**
 *
 * @author ripal
 */
public class listItem extends javax.swing.JDialog {

	int xx,xy;
	private serviceItem service = new DAO_Items();
	private tableModelItem tabelModel = new tableModelItem();
	public modelItem itemSetterGetter = new modelItem();
	public listItem(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		tableItemList.setModel(tabelModel);
		loadData();
		
		
//		

 
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                headerPanel = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                contentPanel = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tableItemList = new javax.swing.JTable();
                searchField = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                completeButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setUndecorated(true);
                addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                formMouseDragged(evt);
                        }
                });
                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                formMousePressed(evt);
                        }
                });

                mainPanel.setLayout(new java.awt.BorderLayout());

                headerPanel.setBackground(new java.awt.Color(0, 0, 255));
                headerPanel.setLayout(new java.awt.BorderLayout());

                jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("DAFTAR BARANG");
                headerPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

                contentPanel.setBackground(new java.awt.Color(255, 255, 255));

                tableItemList.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tableItemList.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tableItemListMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tableItemList);

                searchField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
                searchField.setForeground(java.awt.Color.gray);
                searchField.setText("Masukan Nama Barang");
                searchField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
                searchField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                searchFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                searchFieldFocusLost(evt);
                        }
                });

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/HomeApp/searchItems.png"))); // NOI18N

                completeButton.setText("Selesai");
                completeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                completeButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
                contentPanel.setLayout(contentPanelLayout);
                contentPanelLayout.setHorizontalGroup(
                        contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(completeButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                contentPanelLayout.setVerticalGroup(
                        contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(searchField)
                                        .addComponent(completeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
                );

                headerPanel.add(contentPanel, java.awt.BorderLayout.PAGE_END);

                mainPanel.add(headerPanel, java.awt.BorderLayout.CENTER);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
                xx = evt.getX();
		xy = evt.getY();
        }//GEN-LAST:event_formMousePressed

        private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
               int x,y;
	       x=evt.getXOnScreen();
	       y=evt.getYOnScreen();
	       
	       this.setLocation(x-xx,y-xy);
        }//GEN-LAST:event_formMouseDragged

        private void completeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeButtonActionPerformed
                dispose();
        }//GEN-LAST:event_completeButtonActionPerformed

        private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
                String text = searchField.getText();
		if (text.equals("Masukan Nama Barang")) {
			searchField.setText("");
			searchField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
                        searchField.setForeground(java.awt.Color.black);
		}
        }//GEN-LAST:event_searchFieldFocusGained

        private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
                String text = searchField.getText();
		if (text.equals("")) {
			searchField.setText("Masukan Nama Barang");
			searchField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
                        searchField.setForeground(java.awt.Color.gray);
		}
        }//GEN-LAST:event_searchFieldFocusLost

        private void tableItemListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItemListMouseClicked
                dataChoose();
        }//GEN-LAST:event_tableItemListMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(listItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(listItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(listItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(listItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				listItem dialog = new listItem(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton completeButton;
        private javax.swing.JPanel contentPanel;
        private javax.swing.JPanel headerPanel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JTextField searchField;
        private javax.swing.JTable tableItemList;
        // End of variables declaration//GEN-END:variables

private void dataChoose(){
	int row = tableItemList.getSelectedRow();
	
	itemSetterGetter.setItemCode(tableItemList.getModel().getValueAt(row, 1).toString());
	itemSetterGetter.setItemName(tableItemList.getModel().getValueAt(row, 4).toString());
	itemSetterGetter.setItemUnit(tableItemList.getModel().getValueAt(row, 5).toString());
	itemSetterGetter.setPrice(Integer.parseInt(tableItemList.getModel().getValueAt(row, 6).toString()) );
	dispose();
}

private void searching(){
	List <modelItem>list = service.searchingData(searchField.getText());
	tabelModel.setData(list);
}

private void loadData(){
	List<modelItem>list = service.getData();
	tabelModel.setData(list);
}

}

