package edu.unindra.kkp_kelompok4.home;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

/**
 *
 * @author fadli
 */
public class menuIcon extends javax.swing.JPanel {

	
    public ArrayList<menuIcon> getSubMenu() {
        return subMenu;
    }

    private final ArrayList<menuIcon>subMenu = new ArrayList<>();
    /**
     * Creates new form menuIcon
     */
    private ActionListener act;
    public menuIcon(Icon icon,boolean sbm,Icon iconSub,String menuName,Icon dropDownIcon,Icon dropDownCloseIcon,ActionListener act,menuIcon...subMenu) {
        initComponents();
       
        lb_Icon.setIcon(icon);
        lb_menuname.setText(menuName);
        lb_iconSub.setIcon(iconSub);
        lb_iconSub.setVisible(sbm);
        lib_dropDown.setIcon(dropDownIcon);
	lib_dropDownClose.setIcon(dropDownCloseIcon); 
	lib_dropDown.setVisible(true);
	lib_dropDownClose.setVisible(false);
        if(act != null){
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 45));
        this.setMaximumSize(new Dimension (Integer.MAX_VALUE,45));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE,45));
        for(int i = 0; i< subMenu.length; i++){
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lb_menuname = new javax.swing.JLabel();
                lb_iconSub = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                lib_dropDownClose = new javax.swing.JLabel();
                lib_dropDown = new javax.swing.JLabel();
                lb_Icon = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 255, 255));
                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                formMousePressed(evt);
                        }
                });

                jPanel1.setBackground(new java.awt.Color(255, 204, 51));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lb_menuname.setText("Menu Item...");

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lib_dropDownClose.setBackground(new java.awt.Color(255, 255, 255));
                lib_dropDownClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jPanel2.add(lib_dropDownClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 37, 50));

                lib_dropDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jPanel2.add(lib_dropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 37, 50));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lb_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_iconSub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(lb_menuname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(205, 205, 205)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lb_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_iconSub, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lb_menuname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents
private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        setBackground(new java.awt.Color(255,255,255));
        if (showing){
            hideMenu();
	    lib_dropDown.setVisible(true);
	    lib_dropDownClose.setVisible(false);
        }else{
            showMenu();
	    lib_dropDownClose.setVisible(true);
	    lib_dropDown.setVisible(false);
	    
        }
        if(act != null){
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel lb_Icon;
        private javax.swing.JLabel lb_iconSub;
        private javax.swing.JLabel lb_menuname;
        private javax.swing.JLabel lib_dropDown;
        private javax.swing.JLabel lib_dropDownClose;
        // End of variables declaration//GEN-END:variables

    private void hideMenu() {
       new Thread (new Runnable(){
           public void run(){
               for (int i = subMenu.size() - 1;i>=0;i--){
                   sleep();
                   subMenu.get(i).setVisible(false);
                   subMenu.get(i).hideMenu();
		   
                   
               }
	       showing = false;
               getParent().repaint();
               getParent().revalidate();
              
           }
       }).start();
    }

    private void showMenu() {
        new Thread (new Runnable(){
           public void run(){
               for (int i = 0; i<subMenu.size();i++){
                   sleep();
                   subMenu.get(i).setVisible(true);
                   
               }
               
               showing = true;
                getParent().repaint();
               getParent().revalidate();
           }  
        }).start();
    }

            private void sleep() {
            try{
                Thread.sleep(1);
                
            }catch(Exception e){
                
            }
            }
}            
     
