/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.master;

import edu.unindra.kkp_kelompok4.TableModel.tableModelDistributor;
import edu.unindra.kkp_kelompok4.dao.DAO_Distributor;
import java.util.List;
import edu.unindra.kkp_kelompok4.Services.serviceDistributor;
import edu.unindra.kkp_kelompok4.model.modelDistributor;
import javax.swing.JOptionPane;

/**
 *
 * @author ripal
 */
public class distributorForm extends javax.swing.JPanel {
	
    private serviceDistributor service = new DAO_Distributor();
    private tableModelDistributor table_ModelDistributor = new tableModelDistributor();
    public distributorForm() {
        initComponents();
	disTable.setModel(table_ModelDistributor);
	loadData();
        idDistri.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                dataPanel = new javax.swing.JPanel();
                titleLabel = new javax.swing.JLabel();
                addButton = new javax.swing.JButton();
                deleteButton = new javax.swing.JButton();
                cancelButtonMain = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                disTable = new javax.swing.JTable();
                addPanel = new javax.swing.JPanel();
                titleLabel1 = new javax.swing.JLabel();
                cancelButton = new javax.swing.JButton();
                add_Button = new javax.swing.JButton();
                addDistributor = new javax.swing.JPanel();
                lbId = new javax.swing.JLabel();
                lbAdress = new javax.swing.JLabel();
                lbName = new javax.swing.JLabel();
                lbPhone = new javax.swing.JLabel();
                idPanel = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                idDistri = new javax.swing.JTextField();
                nameDistributorPanel = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                nameDistri = new javax.swing.JTextField();
                phoneNumberPanel = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                phoneDistri = new javax.swing.JTextField();
                addressPanel = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                addressDistri = new javax.swing.JTextField();

                setLayout(new java.awt.CardLayout());

                mainPanel.setLayout(new java.awt.CardLayout());

                dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                titleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel.setText("DATA DISTRIBUTOR");
                dataPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, -1, 54));

                addButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                addButton.setText("Tambah");
                addButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addButtonActionPerformed(evt);
                        }
                });
                dataPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 89, 32));

                deleteButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                deleteButton.setText("Hapus");
                deleteButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteButtonActionPerformed(evt);
                        }
                });
                dataPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 74, 89, 32));

                cancelButtonMain.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                cancelButtonMain.setText("Batal");
                cancelButtonMain.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonMainActionPerformed(evt);
                        }
                });
                dataPanel.add(cancelButtonMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 74, 89, 32));

                disTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                disTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                disTableMouseClicked(evt);
                        }
                });
                jScrollPane2.setViewportView(disTable);

                dataPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 880, -1));

                mainPanel.add(dataPanel, "card2");

                titleLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel1.setText("Tambah Data Distributor");

                cancelButton.setBackground(new java.awt.Color(255, 0, 0));
                cancelButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                cancelButton.setForeground(new java.awt.Color(255, 255, 255));
                cancelButton.setText("Batal");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                add_Button.setBackground(new java.awt.Color(51, 255, 255));
                add_Button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                add_Button.setText("Tambah");
                add_Button.setToolTipText("");
                add_Button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                add_ButtonActionPerformed(evt);
                        }
                });

                lbId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                lbId.setText("ID Distributor");

                lbAdress.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                lbAdress.setText("Alamat");

                lbName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                lbName.setText("Nama Distributor");

                lbPhone.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                lbPhone.setText("Telepon");

                idPanel.setBackground(new java.awt.Color(255, 255, 255));
                idPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                idPanel.setLayout(new javax.swing.BoxLayout(idPanel, javax.swing.BoxLayout.LINE_AXIS));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_company_35px.png"))); // NOI18N
                idPanel.add(jLabel1);

                idDistri.setBorder(null);
                idPanel.add(idDistri);

                nameDistributorPanel.setBackground(new java.awt.Color(255, 255, 255));
                nameDistributorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                nameDistributorPanel.setLayout(new javax.swing.BoxLayout(nameDistributorPanel, javax.swing.BoxLayout.LINE_AXIS));

                jLabel2.setBackground(new java.awt.Color(255, 255, 255));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_company_35px_2.png"))); // NOI18N
                nameDistributorPanel.add(jLabel2);

                nameDistri.setBorder(null);
                nameDistributorPanel.add(nameDistri);

                phoneNumberPanel.setBackground(new java.awt.Color(255, 255, 255));
                phoneNumberPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                phoneNumberPanel.setLayout(new javax.swing.BoxLayout(phoneNumberPanel, javax.swing.BoxLayout.LINE_AXIS));

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_phone_35px.png"))); // NOI18N
                phoneNumberPanel.add(jLabel3);

                phoneDistri.setBorder(null);
                phoneNumberPanel.add(phoneDistri);

                addressPanel.setBackground(new java.awt.Color(255, 255, 255));
                addressPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                addressPanel.setLayout(new javax.swing.BoxLayout(addressPanel, javax.swing.BoxLayout.LINE_AXIS));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/Master/icons8_address_35px.png"))); // NOI18N
                addressPanel.add(jLabel4);

                addressDistri.setBorder(null);
                addressPanel.add(addressDistri);

                javax.swing.GroupLayout addDistributorLayout = new javax.swing.GroupLayout(addDistributor);
                addDistributor.setLayout(addDistributorLayout);
                addDistributorLayout.setHorizontalGroup(
                        addDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addDistributorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameDistributorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(addDistributorLayout.createSequentialGroup()
                                                .addGroup(addDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbName)
                                                        .addComponent(lbId)
                                                        .addComponent(lbPhone)
                                                        .addComponent(lbAdress))
                                                .addGap(0, 1025, Short.MAX_VALUE))
                                        .addComponent(addressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                addDistributorLayout.setVerticalGroup(
                        addDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addDistributorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameDistributorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(lbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
                addPanel.setLayout(addPanelLayout);
                addPanelLayout.setHorizontalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleLabel1)
                                        .addGroup(addPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addDistributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(addPanelLayout.createSequentialGroup()
                                                                .addComponent(add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
                );
                addPanelLayout.setVerticalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                mainPanel.add(addPanel, "card2");

                add(mainPanel, "card2");
        }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        mainPanel.removeAll();
	mainPanel.repaint();
	mainPanel.revalidate();
	
        mainPanel.add(addPanel);
	mainPanel.repaint();
	mainPanel.revalidate();
	
	
	add_Button.setText("Simpan");
	//selectItem.setEnabled(true);
	idDistri.setText(service.number());
	
	    if (addButton.getText().equals("Ubah")) {
		    dataTable();
	    }
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
	    panelDisplay();
	    loadData();
	    resetForm();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
        if (add_Button.getText().equals("Tambah")) {
		    add_Button.setText("Simpan");
		    idDistri.setText(service.number());
	    }else if(add_Button.getText().equals("Simpan")){
		    saveData();
	    }else if(add_Button.getText().equals("Perbarui")){
		    renewData();
	    }
    }//GEN-LAST:event_add_ButtonActionPerformed

        private void cancelButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonMainActionPerformed
               panelDisplay();
	       loadData();
	       resetForm();
        }//GEN-LAST:event_cancelButtonMainActionPerformed

        private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
               int index = disTable.getSelectedRow();
	       
	       if (index!=-1){
		       modelDistributor model= table_ModelDistributor.getData(disTable.convertRowIndexToModel(index));
		       if (JOptionPane.showConfirmDialog(null, "Apakah ingin menghapus data ini ?","Konfirmasi hapus data",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION) {
			       service.deleteData(model);
			       table_ModelDistributor.deleteData(index);
			       loadData();
			       resetForm();
		       }else{
			       JOptionPane.showMessageDialog(null, "data gagal dihapus");
		       }
	       }
        }//GEN-LAST:event_deleteButtonActionPerformed

    private void disTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disTableMouseClicked
         if (addButton.getText().equals("Tambah")) {
			addButton.setText("Ubah");
		}
		deleteButton.setVisible(true);
		cancelButtonMain.setVisible(true);
    }//GEN-LAST:event_disTableMouseClicked

private void panelDisplay(){
	mainPanel.removeAll();
	mainPanel.add(new distributorForm());
        mainPanel.repaint();
        mainPanel.revalidate();
}




        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addButton;
        private javax.swing.JPanel addDistributor;
        private javax.swing.JPanel addPanel;
        private javax.swing.JButton add_Button;
        private javax.swing.JTextField addressDistri;
        private javax.swing.JPanel addressPanel;
        private javax.swing.JButton cancelButton;
        private javax.swing.JButton cancelButtonMain;
        private javax.swing.JPanel dataPanel;
        private javax.swing.JButton deleteButton;
        private javax.swing.JTable disTable;
        private javax.swing.JTextField idDistri;
        private javax.swing.JPanel idPanel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel lbAdress;
        private javax.swing.JLabel lbId;
        private javax.swing.JLabel lbName;
        private javax.swing.JLabel lbPhone;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JTextField nameDistri;
        private javax.swing.JPanel nameDistributorPanel;
        private javax.swing.JTextField phoneDistri;
        private javax.swing.JPanel phoneNumberPanel;
        private javax.swing.JLabel titleLabel;
        private javax.swing.JLabel titleLabel1;
        // End of variables declaration//GEN-END:variables

	
	private void loadData(){
	deleteButton.setVisible(false);
	cancelButtonMain.setVisible(false);
	List<modelDistributor> list =service.getData();
	table_ModelDistributor.setData(list);

}
	
	private void saveData(){
		if (validasiInput()==true){
			String ID = idDistri.getText();
			String nameDis = nameDistri.getText();
			String phoneDis = phoneDistri.getText();
			String addressDis = addressDistri.getText();
			
			
			modelDistributor model = new modelDistributor();
			model.setDistributorId(ID);
                        model.setDistributorName(nameDis);
                        model.setDistributorTlp(phoneDis);
                        model.setDistributorAddress(addressDis);
			
			
			
			service.addData(model);
			table_ModelDistributor.addData(model);
			loadData();
			resetForm();
			panelDisplay();
			add_Button.setText("Tambah");
			
		
		}
	}
	
	private boolean validasiInput(){
		boolean valid=false;
		if (idDistri.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, "ID Tidak Boleh Kosong");
		}else if (nameDistri.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "Nama tidak boleh Kosong");
		}else if (phoneDistri.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "No telp tidak boleh Kosong");
		}else if (addressDistri.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "Alamat tidak boleh Kosong");
		}else{
			valid=true;
		}
		return valid;
	}
	
	private void renewData(){
		int index = disTable.getSelectedRow();
		if (index!=-1){
			modelDistributor mod_dis = table_ModelDistributor.getData(disTable.convertRowIndexToModel(index));
		
                        
			if (validasiInput()==true){
			String ID = idDistri.getText();
			String nameDis = nameDistri.getText();
			String phoneDis = phoneDistri.getText();
			String addressDis = addressDistri.getText();
			
			
			modelDistributor model = new modelDistributor();
			model.setDistributorId(ID);
                        model.setDistributorName(nameDis);
                        model.setDistributorTlp(phoneDis);
                        model.setDistributorAddress(addressDis);
				
				service.renewData(model);
				table_ModelDistributor.renewItem(index,model);
				loadData();
				resetForm();
				panelDisplay();
				
			}
		}
	}
	
	private void resetForm(){
		addButton.requestFocus();
		addButton.setText("Tambah");
		idDistri.setText("");
		nameDistri.setText("");
		phoneDistri.setText("");
		addressDistri.setText("");
	}

	private void dataTable(){
		dataPanel.setVisible(false);
		addPanel.setVisible(true);
		
		int row = disTable.getSelectedRow();
		titleLabel1.setText("Perbarui Data Barang");
		
		idDistri.setEnabled(false);
		nameDistri.setEnabled(true);
		phoneDistri.setEnabled(true);
		
		idDistri.setText(disTable.getModel().getValueAt(row, 1).toString());
		nameDistri.setText(disTable.getModel().getValueAt(row, 2).toString());
		phoneDistri.setText(disTable.getModel().getValueAt(row, 3).toString());
		addressDistri.setText(disTable.getModel().getValueAt(row, 4).toString());
		
		add_Button.setText("Perbarui");
		cancelButtonMain.setVisible(true);
	}

//private void search(){
//    List<modelDistributor> list = service.searching(tSearch.getText());
//}





}



