/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.master;

import edu.unindra.kkp_kelompok4.TableModel.tableModelItem;
import edu.unindra.kkp_kelompok4.dao.DAO_Items;
import edu.unindra.kkp_kelompok4.model.modelItem;
import java.util.List;
import edu.unindra.kkp_kelompok4.Services.serviceItem;
import edu.unindra.kkp_kelompok4.Services.serviceReport;
import edu.unindra.kkp_kelompok4.dao.DAO_Report;
import edu.unindra.kkp_kelompok4.model.modelTypeItem;
import edu.unindra.kkp_kelompok4.resource.koneksi;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ripal
 */
public class itemForm extends javax.swing.JPanel {
    private modelTypeItem type = new modelTypeItem();
    private serviceItem service = new DAO_Items();
    private serviceReport reportService = new DAO_Report();
    private tableModelItem tabelModel = new tableModelItem();
    public itemForm() {
        initComponents();
	itemTable.setModel(tabelModel);
	loadData();
	itemCode.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                dataPanel = new javax.swing.JPanel();
                titleLabel = new javax.swing.JLabel();
                addButton = new javax.swing.JButton();
                deleteButton = new javax.swing.JButton();
                cancelButtonMain = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                itemTable = new javax.swing.JTable();
                printButton = new javax.swing.JButton();
                addPanel = new javax.swing.JPanel();
                titleLabel1 = new javax.swing.JLabel();
                cancelButton = new javax.swing.JButton();
                add_Button = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jcRole = new javax.swing.JPanel();
                kodeBarang = new javax.swing.JLabel();
                itemCode = new javax.swing.JTextField();
                itemNameLabel = new javax.swing.JLabel();
                itemName = new javax.swing.JTextField();
                unitLabel = new javax.swing.JLabel();
                typeItemLabel = new javax.swing.JLabel();
                stockLabel = new javax.swing.JLabel();
                listItemCode = new javax.swing.JTextField();
                selectItem = new javax.swing.JButton();
                price = new javax.swing.JLabel();
                stockField = new javax.swing.JTextField();
                pricePanel = new javax.swing.JPanel();
                priceItem = new javax.swing.JTextField();
                itemTypeNameLabel = new javax.swing.JLabel();
                typeItemName = new javax.swing.JTextField();
                unitItem = new javax.swing.JComboBox<>();

                setLayout(new java.awt.CardLayout());

                mainPanel.setLayout(new java.awt.CardLayout());

                titleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel.setText("Data Barang");

                addButton.setBackground(new java.awt.Color(102, 51, 255));
                addButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                addButton.setForeground(new java.awt.Color(255, 255, 255));
                addButton.setText("Tambah");
                addButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addButtonActionPerformed(evt);
                        }
                });

                deleteButton.setBackground(new java.awt.Color(255, 0, 0));
                deleteButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                deleteButton.setForeground(new java.awt.Color(255, 255, 255));
                deleteButton.setText("Hapus");
                deleteButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteButtonActionPerformed(evt);
                        }
                });

                cancelButtonMain.setBackground(new java.awt.Color(0, 153, 153));
                cancelButtonMain.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                cancelButtonMain.setForeground(new java.awt.Color(255, 255, 255));
                cancelButtonMain.setText("Batal");
                cancelButtonMain.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonMainActionPerformed(evt);
                        }
                });

                itemTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                itemTableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(itemTable);

                printButton.setBackground(java.awt.SystemColor.textHighlight);
                printButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                printButton.setForeground(new java.awt.Color(255, 255, 255));
                printButton.setText("Cetak");
                printButton.setActionCommand("Print");
                printButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                printButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
                dataPanel.setLayout(dataPanelLayout);
                dataPanelLayout.setHorizontalGroup(
                        dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleLabel)
                                        .addGroup(dataPanelLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cancelButtonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                dataPanelLayout.setVerticalGroup(
                        dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelButtonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                );

                mainPanel.add(dataPanel, "card2");

                titleLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel1.setText("Tambah Data Barang");

                cancelButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                cancelButton.setText("Batal");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                add_Button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                add_Button.setText("Tambah");
                add_Button.setToolTipText("");
                add_Button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                add_ButtonActionPerformed(evt);
                        }
                });

                jScrollPane2.setBorder(null);

                jcRole.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                kodeBarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                kodeBarang.setText("Kode Barang");
                jcRole.add(kodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 31));

                itemCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jcRole.add(itemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, 715, 33));

                itemNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                itemNameLabel.setText("Nama Barang");
                jcRole.add(itemNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 291, -1, 31));

                itemName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jcRole.add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 329, 715, 33));

                unitLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                unitLabel.setText("Satuan");
                jcRole.add(unitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 380, -1, 31));

                typeItemLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                typeItemLabel.setText("Kode Jenis Barang");
                jcRole.add(typeItemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, 31));

                stockLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                stockLabel.setText("Stock");
                jcRole.add(stockLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, 30));

                listItemCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jcRole.add(listItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 140, 631, 33));

                selectItem.setText("Pilih");
                selectItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                selectItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selectItemActionPerformed(evt);
                        }
                });
                jcRole.add(selectItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 140, 66, 33));

                price.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                price.setText("Harga");
                jcRole.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 480, -1, 31));

                stockField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jcRole.add(stockField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 720, 30));

                pricePanel.setBackground(new java.awt.Color(255, 255, 255));
                pricePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                pricePanel.setLayout(new javax.swing.BoxLayout(pricePanel, javax.swing.BoxLayout.LINE_AXIS));

                priceItem.setBorder(null);
                priceItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                priceItemActionPerformed(evt);
                        }
                });
                pricePanel.add(priceItem);

                jcRole.add(pricePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 720, 30));

                itemTypeNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                itemTypeNameLabel.setText("Nama Jenis Barang");
                jcRole.add(itemTypeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 191, -1, 31));

                typeItemName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jcRole.add(typeItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, 715, 33));

                unitItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Satuan -", "Kilogram", "Liter", "Gram", "Bungkus", "Pack", "Buah", "Sachet", "Dos", "Roll", "Packets", "Carton", "Pack of", "Piece", "Box\t", "Botol", "Literan (ltr)" }));
                unitItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jcRole.add(unitItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 429, 715, 33));

                jScrollPane2.setViewportView(jcRole);

                javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
                addPanel.setLayout(addPanelLayout);
                addPanelLayout.setHorizontalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleLabel1)
                                        .addGroup(addPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                                                        .addGroup(addPanelLayout.createSequentialGroup()
                                                                .addComponent(add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
                );
                addPanelLayout.setVerticalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                );

                mainPanel.add(addPanel, "card2");

                add(mainPanel, "card2");
        }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
	    panelDisplay();
	    loadData();
	    resetForm();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
        if (add_Button.getText().equals("Tambah")) {
		    add_Button.setText("Simpan");
		    itemCode.setText(service.number());
	    }else if(add_Button.getText().equals("Simpan")){
		    saveData();
	    }else if(add_Button.getText().equals("Perbarui")){
		    renewData();
	    }
    }//GEN-LAST:event_add_ButtonActionPerformed

        private void selectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemActionPerformed
                boolean closable= true;
		dataItemList dataItem = new dataItemList(null,closable);
		dataItem.setVisible(true);
		
		listItemCode.setText(dataItem.typeItems.getCodeType());
		typeItemName.setText(dataItem.typeItems.getNameType());

		itemName.requestFocus();
                String checkField = listItemCode.getText();
                if (!checkField.equals("")) {
                enableField();
            }
		
		

		
        }//GEN-LAST:event_selectItemActionPerformed

    private void priceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceItemActionPerformed

        private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
		reportService.reportItem();
		
               

        }//GEN-LAST:event_printButtonActionPerformed

        private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
                if (addButton.getText().equals("Tambah")) {
                        addButton.setText("Ubah");
                }
                deleteButton.setVisible(true);
                cancelButtonMain.setVisible(true);
        }//GEN-LAST:event_itemTableMouseClicked

        private void cancelButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonMainActionPerformed
                panelDisplay();
                loadData();
                resetForm();
        }//GEN-LAST:event_cancelButtonMainActionPerformed

        private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
                int index = itemTable.getSelectedRow();

                if (index!=-1){
                        modelItem item = tabelModel.getData(itemTable.convertRowIndexToModel(index));
                        if (JOptionPane.showConfirmDialog(null, "Apakah ingin menghapus data ini ?","Konfirmasi hapus data",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION) {
                                service.deleteItem(item);
                                tabelModel.deleteItem(index);
                                loadData();
                                resetForm();
                        }else{
                                JOptionPane.showMessageDialog(null, "data gagal dihapus");
                        }
                }
        }//GEN-LAST:event_deleteButtonActionPerformed

        private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
                mainPanel.removeAll();
                mainPanel.repaint();
                mainPanel.revalidate();

                mainPanel.add(addPanel);
                mainPanel.repaint();
                mainPanel.revalidate();

                add_Button.setText("Simpan");
                selectItem.setEnabled(true);
                itemCode.setText(service.number());

                if (addButton.getText().equals("Ubah")) {
                        dataTable();
                        listItemCode.setEnabled(false);
                        typeItemName.setEnabled(false);
                }
        }//GEN-LAST:event_addButtonActionPerformed

private void panelDisplay(){
	mainPanel.removeAll();
	mainPanel.add(new itemForm());
        mainPanel.repaint();
        mainPanel.revalidate();
}

private void disableField(){
	listItemCode.setEnabled(false);
	typeItemName.setEnabled(false);
	itemName.setEnabled(false);
	unitItem.setEnabled(false);
	priceItem.setEnabled(false);
	stockField.setEnabled(false);
	
}

private void enableField(){
	itemName.setEnabled(true);
	unitItem.setEnabled(true);
	priceItem.setEnabled(true);
	stockField.setEnabled(true);
	
}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addButton;
        private javax.swing.JPanel addPanel;
        private javax.swing.JButton add_Button;
        private javax.swing.JButton cancelButton;
        private javax.swing.JButton cancelButtonMain;
        private javax.swing.JPanel dataPanel;
        private javax.swing.JButton deleteButton;
        private javax.swing.JTextField itemCode;
        private javax.swing.JTextField itemName;
        private javax.swing.JLabel itemNameLabel;
        private javax.swing.JTable itemTable;
        private javax.swing.JLabel itemTypeNameLabel;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JPanel jcRole;
        private javax.swing.JLabel kodeBarang;
        private javax.swing.JTextField listItemCode;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JLabel price;
        private javax.swing.JTextField priceItem;
        private javax.swing.JPanel pricePanel;
        private javax.swing.JButton printButton;
        private javax.swing.JButton selectItem;
        private javax.swing.JTextField stockField;
        private javax.swing.JLabel stockLabel;
        private javax.swing.JLabel titleLabel;
        private javax.swing.JLabel titleLabel1;
        private javax.swing.JLabel typeItemLabel;
        private javax.swing.JTextField typeItemName;
        private javax.swing.JComboBox<String> unitItem;
        private javax.swing.JLabel unitLabel;
        // End of variables declaration//GEN-END:variables

	
	private void loadData(){
	deleteButton.setVisible(false);
	cancelButtonMain.setVisible(false);
	List<modelItem> list =service.getData();
	tabelModel.setData(list);
	disableField();
}
	
	private void saveData(){
		if (validasiInput()==true){
			String codeItem = itemCode.getText();
			String typeCode = listItemCode.getText();
			String nameType = typeItemName.getText();
			String nameItem = itemName.getText();
			String unit	= unitItem.getSelectedItem().toString();
			int price	= Integer.parseInt(priceItem.getText());
			int Stock	= Integer.parseInt(stockField.getText());
			
			modelItem item = new modelItem();
			
			
			item.setItemCode(codeItem);
			type.setCodeType(typeCode);
			type.setNameType(nameType);
			item.setItemName(nameItem);
			item.setItemUnit(unit);
			item.setPrice(price);
			item.setStock(Stock);
			
			item.setType_item(type);
			
			service.addItem(item);
			tabelModel.addItem(item);
			loadData();
			resetForm();
			panelDisplay();
			add_Button.setText("Tambah");
			
		
		}
	}
	
	private boolean validasiInput(){
		boolean input=false;
		if (itemCode.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
		}else if (listItemCode.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "Kode Jenis Barang tidak boleh kosong");
		}else if (typeItemName.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "Nama Jenis Barang tidak boleh kosong");
		}else if (itemName.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong");
		}else if (unitItem.getSelectedItem().equals(null)){
			JOptionPane.showMessageDialog(null, "Satuan tidak boleh kosong");
		}else if (stockField.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "Stock tidak boleh kosong");
		}else{
			input=true;
		}
		return input;
	}
	
	private void renewData(){
		int index = itemTable.getSelectedRow();
		if (index!=-1){
			modelItem model_Item = tabelModel.getData(itemTable.convertRowIndexToModel(index));
			
			if (validasiInput()==true){
				String codeItem = itemCode.getText();
				String typeCode = listItemCode.getText();
				String nameType = typeItemName.getText();
				String nameItem = itemName.getText();
				String unit	= unitItem.getSelectedItem().toString();
				int price	= Integer.parseInt(priceItem.getText());
				int Stock	= Integer.parseInt(stockField.getText());

				modelItem item = new modelItem();
				modelTypeItem type = new modelTypeItem();

				item.setItemCode(codeItem);
				type.setCodeType(typeCode);
				type.setNameType(nameType);
				item.setItemName(nameItem);
				item.setItemUnit(unit);
				item.setPrice(price);
				item.setStock(Stock);

				item.setType_item(type);
				
				service.renewItem(item);
				tabelModel.renewItem(index, item);
				loadData();
				resetForm();
				panelDisplay();
				
			}
		}
	}
	
	private void resetForm(){
		addButton.requestFocus();
		addButton.setText("Tambah");
		itemCode.setText("");
		listItemCode.setText("");
		typeItemName.setText("");
		itemName.setText("");
		unitItem.setSelectedItem(0);
		priceItem.setText("");
		stockField.setText("");
	}

	private void dataTable(){
		dataPanel.setVisible(false);
		addPanel.setVisible(true);
		
		int row = itemTable.getSelectedRow();
		titleLabel1.setText("Perbarui Data Barang");
		
		itemCode.setEnabled(false);
		listItemCode.setEnabled(true);
		typeItemName.setEnabled(true);
		
		itemCode.setText(itemTable.getModel().getValueAt(row, 1).toString());
		listItemCode.setText(itemTable.getModel().getValueAt(row, 2).toString());
		typeItemName.setText(itemTable.getModel().getValueAt(row, 3).toString());
		itemName.setText(itemTable.getModel().getValueAt(row, 4).toString());
		unitItem.setSelectedItem(itemTable.getModel().getValueAt(row, 5).toString());
		priceItem.setText(itemTable.getModel().getValueAt(row, 6).toString());
		stockField.setText(itemTable.getModel().getValueAt(row, 7).toString());
		
		enableField();
		add_Button.setText("Perbarui");
		cancelButtonMain.setVisible(true);
	}







}



