/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.master;

import java.util.List;
import edu.unindra.kkp_kelompok4.Services.serviceTypeItem;
import edu.unindra.kkp_kelompok4.TableModel.tableModelTypeItem;
import edu.unindra.kkp_kelompok4.dao.DAO_typeItem;
import edu.unindra.kkp_kelompok4.model.modelTypeItem;
import javax.swing.JOptionPane;

/**
 *
 * @author ripal
 */
public class itemTypeListForm extends javax.swing.JPanel {
    private modelTypeItem type = new modelTypeItem();
    private serviceTypeItem service = new DAO_typeItem();
    private tableModelTypeItem tabelModel = new tableModelTypeItem();
    public itemTypeListForm() {
        initComponents();
	typeTable.setModel(tabelModel);
	loadData();
        itemTypeCode.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        cancelButtonMain = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        typeTable = new javax.swing.JTable();
        addPanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        add_Button = new javax.swing.JButton();
        addItem = new javax.swing.JPanel();
        kodeBarang = new javax.swing.JLabel();
        itemTypeCode = new javax.swing.JTextField();
        itemTypeNameLabel = new javax.swing.JLabel();
        typeItemName = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        titleLabel.setText("Data Jenis Barang");
        dataPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, -1, 54));

        addButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        addButton.setText("Tambah");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        dataPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 89, 32));

        deleteButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        dataPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 74, 89, 32));

        cancelButtonMain.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cancelButtonMain.setText("Batal");
        cancelButtonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonMainActionPerformed(evt);
            }
        });
        dataPanel.add(cancelButtonMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 74, 89, 32));

        typeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        typeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(typeTable);

        dataPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 740, 370));

        mainPanel.add(dataPanel, "card2");

        titleLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        titleLabel1.setText("Tambah Data Jenis Barang");

        cancelButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cancelButton.setText("Batal");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        add_Button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        add_Button.setText("Tambah");
        add_Button.setToolTipText("");
        add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ButtonActionPerformed(evt);
            }
        });

        kodeBarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        kodeBarang.setText("Kode Jenis Barang");

        itemTypeCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        itemTypeNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        itemTypeNameLabel.setText("Nama Jenis Barang");

        typeItemName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout addItemLayout = new javax.swing.GroupLayout(addItem);
        addItem.setLayout(addItemLayout);
        addItemLayout.setHorizontalGroup(
            addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemTypeCode)
                    .addComponent(typeItemName)
                    .addGroup(addItemLayout.createSequentialGroup()
                        .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodeBarang)
                            .addComponent(itemTypeNameLabel))
                        .addGap(0, 584, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addItemLayout.setVerticalGroup(
            addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemTypeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(itemTypeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(typeItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel1)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        mainPanel.add(addPanel, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        mainPanel.removeAll();
	mainPanel.repaint();
	mainPanel.revalidate();
	
        mainPanel.add(addPanel);
	mainPanel.repaint();
	mainPanel.revalidate();
	
	add_Button.setText("Simpan");
	itemTypeCode.setText(service.numbering());
	
	    if (addButton.getText().equals("Ubah")) {
		    dataTable();
		    itemTypeCode.setEnabled(false);
		    typeItemName.setEnabled(true);
	    }
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
	    panelDisplay();
	    loadData();
	    resetForm();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
        if (add_Button.getText().equals("Tambah")) {
		    add_Button.setText("Simpan");
		    itemTypeCode.setText(service.numbering());
	    }else if(add_Button.getText().equals("Simpan")){
		    saveData();
	    }else if(add_Button.getText().equals("Perbarui")){
		    renewData();
	    }
    }//GEN-LAST:event_add_ButtonActionPerformed

        private void cancelButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonMainActionPerformed
               panelDisplay();
	       loadData();
	       resetForm();
        }//GEN-LAST:event_cancelButtonMainActionPerformed

        private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
               int index = typeTable.getSelectedRow();
	       
	       if (index!=-1){
		       modelTypeItem item = tabelModel.getData(typeTable.convertRowIndexToModel(index));
		       if (JOptionPane.showConfirmDialog(null, "Apakah ingin menghapus data ini ?","Konfirmasi hapus data",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION) {
			       service.deleteItem(item);
			       tabelModel.deleteItem(index);
			       loadData();
			       resetForm();
		       }else{
			       JOptionPane.showMessageDialog(null, "data gagal dihapus");
		       }
	       }
        }//GEN-LAST:event_deleteButtonActionPerformed

    private void typeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeTableMouseClicked
         if (addButton.getText().equals("Tambah")) {
			addButton.setText("Ubah");
		}
		deleteButton.setVisible(true);
		cancelButtonMain.setVisible(true);
    }//GEN-LAST:event_typeTableMouseClicked

private void panelDisplay(){
	mainPanel.removeAll();
	mainPanel.add(new itemTypeListForm());
        mainPanel.repaint();
        mainPanel.revalidate();
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addItem;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton add_Button;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButtonMain;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField itemTypeCode;
    private javax.swing.JLabel itemTypeNameLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kodeBarang;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JTextField typeItemName;
    private javax.swing.JTable typeTable;
    // End of variables declaration//GEN-END:variables

	
	private void loadData(){
	deleteButton.setVisible(false);
	cancelButtonMain.setVisible(false);
	List<modelTypeItem> list =service.getItems();
	tabelModel.setData(list);
	;
}
	
	private void saveData(){
		if (validasiInput()==true){
			String codeItem = itemTypeCode.getText();
			String nameType = typeItemName.getText();
			
                        type.setCodeType(codeItem);
			type.setNameType(nameType);
			
			service.addItem(type);
			tabelModel.addItem(type);
			loadData();
			resetForm();
			panelDisplay();
			add_Button.setText("Tambah");
			
		
		}
	}
	
	private boolean validasiInput(){
		boolean input=false;
		if (itemTypeCode.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Kode Jenis Barang tidak boleh kosong");
		}else if (typeItemName.getText().trim().isEmpty()){
			JOptionPane.showMessageDialog(null, "Nama Jenis Barang tidak boleh kosong");
		}else{
			input=true;
		}
		return input;
	}
	
	private void renewData(){
		int index = typeTable.getSelectedRow();
		if (index!=-1){
			modelTypeItem modis = tabelModel.getData(typeTable.convertRowIndexToModel(index));
			
			if (validasiInput()==true){
				String codeItem = itemTypeCode.getText();
				String nameType = typeItemName.getText();

				modelTypeItem type = new modelTypeItem();

				type.setCodeType(codeItem);
				type.setNameType(nameType);
				
				service.renewItem(type);
				tabelModel.renewItem(index, type);
				loadData();
				resetForm();
				panelDisplay();
				
			}
		}
	}
	
	private void resetForm(){
		addButton.requestFocus();
		addButton.setText("Tambah");
		itemTypeCode.setText("");
		typeItemName.setText("");
	}

	private void dataTable(){
		dataPanel.setVisible(false);
		addPanel.setVisible(true);
		
		int row = typeTable.getSelectedRow();
		titleLabel1.setText("Perbarui Jenis Barang");
		
		itemTypeCode.setEnabled(false);
		typeItemName.setEnabled(true);
		
		itemTypeCode.setText(typeTable.getModel().getValueAt(row, 1).toString());
		typeItemName.setText(typeTable.getModel().getValueAt(row, 2).toString());
		
		add_Button.setText("Perbarui");
		cancelButtonMain.setVisible(true);
	}







}



