/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.unindra.kkp_kelompok4.cashier;

/**
 *
 * @author ripal
 */
public class aboutApp extends javax.swing.JDialog {

    /**
     * Creates new form aboutApp
     */
    public aboutApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        unindraLogo = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutLabel = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About App");
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unindraLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/unindra.png"))); // NOI18N
        mainPanel.add(unindraLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 200, 180));

        closeButton.setBackground(new java.awt.Color(255, 0, 51));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        mainPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(221, 400));

        aboutLabel.setLabelFor(jScrollPane1);
        aboutLabel.setText("<html>\n<p align=\"justify\">\nAplikasi ini merupakan hasil kerja sama antara kelompok kami yang terdiri dari mahasiswa berbakat yang belajar di jurusan Teknik Informatika. Kami sangat bangga dapat mempersembahkan aplikasi ini kepada Anda dengan harapan dapat memberikan manfaat dan kemudahan dalam kehidupan sehari-hari.\n</p>\n<br>\n<p align=\"justify\">\nKelompok kami terdiri dari tujuh anggota, yaitu:\n<ul>\n  <li>RIPALDIANSYAH &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp; 202043502261</li>\n  <li>FADLILATUL UMAM &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 202043502318</li>\n  <li>YOSUA &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp; 202043502303</li>\n  <li>MUHAMAD ABDUL FIQIH &emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;202043500041</li>\n  <li>IMRO'ATUS AYU SHOLIKHAH &emsp;&emsp;&nbsp;&nbsp;202043500104</li>\n  <li>UBAY BAYHACQI LAZUARDI &emsp;&emsp;&emsp;&nbsp;&nbsp;202043500074</li>\n  <li>JULIANTO &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;202043500003</li>\n</ul>\n</p>\n<p align=\"justify\">\nKami berusaha keras untuk membuat aplikasi yang mudah digunakan dan dapat membantu Anda dalam menyelesaikan tugas-tugas sehari-hari dengan lebih efisien.\n Kami mengembangkan aplikasi ini dengan menggunakan teknologi yang terkini dan selalu memperhatikan kualitas dan keamanannya.\nKami harap Anda dapat menikmati aplikasi ini dan kami siap menerima masukan dan saran dari Anda untuk pengembangan aplikasi kami selanjutnya.\n</p>\n<br>\n<p align=\"justify\">\nTerima kasih atas dukungan dan kepercayaan Anda kepada kami.\n</p>\n</html>");
        aboutLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        aboutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutLabel.setPreferredSize(new java.awt.Dimension(180, 380));
        jScrollPane1.setViewportView(aboutLabel);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 490, 250));
        jScrollPane1.getAccessibleContext().setAccessibleParent(aboutLabel);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        titlePanel.setBackground(new java.awt.Color(204, 204, 204));

        titleLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titleLabel.setText("Aplikasi Cashier XYZ By Kelompok 4");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titleLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(titleLabel)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        getContentPane().add(titlePanel, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel unindraLogo;
    // End of variables declaration//GEN-END:variables
}
