/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.unindra.kkp_kelompok4.cashier;


import edu.unindra.kkp_kelompok4.Services.serviceCashier;
import edu.unindra.kkp_kelompok4.Services.serviceDetailCartCashier;
import edu.unindra.kkp_kelompok4.Services.serviceDetailCashier;
import edu.unindra.kkp_kelompok4.TableModel.tableModelCashierDraft;
import edu.unindra.kkp_kelompok4.TableModel.tableModelDetailCashierDraft;
import edu.unindra.kkp_kelompok4.dao.DAO_Cashier;
import edu.unindra.kkp_kelompok4.dao.DAO_DetailCartCashier;
import edu.unindra.kkp_kelompok4.dao.DAO_DetailCashier;
import edu.unindra.kkp_kelompok4.model.modelCashier;
import edu.unindra.kkp_kelompok4.model.modelCashierCart;
import edu.unindra.kkp_kelompok4.model.modelDetailCashier;
import edu.unindra.kkp_kelompok4.model.modelDetailCashierDraft;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ripal
 */
public class listDraft extends javax.swing.JDialog {

	int xx,xy;
	private serviceCashier service = new DAO_Cashier();
	private serviceDetailCartCashier serviceDetailCartCashier2 = new DAO_DetailCartCashier();
	private serviceDetailCashier servicedetailCashier = new DAO_DetailCashier();
	private tableModelCashierDraft tabelModel = new tableModelCashierDraft();
	private tableModelDetailCashierDraft tabelModelDetailCashier = new tableModelDetailCashierDraft();
	public modelDetailCashierDraft detailCashier = new modelDetailCashierDraft();
	public modelCashier cashierModel = new modelCashier();
	public listDraft(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		tableTransactionList.setModel(tabelModel);
		tableDetailTransactionList.setModel(tabelModelDetailCashier);
		cancelButton.requestFocus();	
		loadData();
		detailTransactionPanel.setVisible(false); 
		changeButton.setVisible(false);
		printButton.setVisible(false);
		hideButton.setVisible(false);
		
		
		
//		

 
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                listTransactionPanel = new javax.swing.JPanel();
                headerListTransactionPanel = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                listTransaction = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tableTransactionList = new javax.swing.JTable();
                searchField = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                cancelButton = new javax.swing.JButton();
                detailTransactionPanel = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                tableDetailTransactionList = new javax.swing.JTable();
                changeButton = new javax.swing.JButton();
                printButton = new javax.swing.JButton();
                hideButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setUndecorated(true);
                addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                formMouseDragged(evt);
                        }
                });
                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                formMousePressed(evt);
                        }
                });

                listTransactionPanel.setLayout(new java.awt.BorderLayout());

                headerListTransactionPanel.setBackground(new java.awt.Color(0, 0, 255));

                jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("DAFTAR DRAFT TRANSAKSI");

                javax.swing.GroupLayout headerListTransactionPanelLayout = new javax.swing.GroupLayout(headerListTransactionPanel);
                headerListTransactionPanel.setLayout(headerListTransactionPanelLayout);
                headerListTransactionPanelLayout.setHorizontalGroup(
                        headerListTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerListTransactionPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                headerListTransactionPanelLayout.setVerticalGroup(
                        headerListTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                );

                listTransactionPanel.add(headerListTransactionPanel, java.awt.BorderLayout.CENTER);

                listTransaction.setBackground(new java.awt.Color(255, 255, 255));

                tableTransactionList.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tableTransactionList.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tableTransactionListMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tableTransactionList);

                searchField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
                searchField.setForeground(java.awt.Color.gray);
                searchField.setText("Masukan Nama Distributor");
                searchField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
                searchField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                searchFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                searchFieldFocusLost(evt);
                        }
                });

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/HomeApp/searchItems.png"))); // NOI18N

                cancelButton.setText("Batal");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout listTransactionLayout = new javax.swing.GroupLayout(listTransaction);
                listTransaction.setLayout(listTransactionLayout);
                listTransactionLayout.setHorizontalGroup(
                        listTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listTransactionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(searchField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)
                                .addGap(21, 21, 21))
                        .addGroup(listTransactionLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                listTransactionLayout.setVerticalGroup(
                        listTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listTransactionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(listTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(searchField)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
                );

                listTransactionPanel.add(listTransaction, java.awt.BorderLayout.PAGE_END);

                tableDetailTransactionList.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tableDetailTransactionList.setToolTipText("");
                tableDetailTransactionList.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tableDetailTransactionListMouseClicked(evt);
                        }
                });
                jScrollPane2.setViewportView(tableDetailTransactionList);

                javax.swing.GroupLayout detailTransactionPanelLayout = new javax.swing.GroupLayout(detailTransactionPanel);
                detailTransactionPanel.setLayout(detailTransactionPanelLayout);
                detailTransactionPanelLayout.setHorizontalGroup(
                        detailTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                );
                detailTransactionPanelLayout.setVerticalGroup(
                        detailTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailTransactionPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                );

                changeButton.setText("Ubah");
                changeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                changeButtonActionPerformed(evt);
                        }
                });

                printButton.setText("Hapus");
                printButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                printButtonActionPerformed(evt);
                        }
                });

                hideButton.setText("Sembunyikan");
                hideButton.setToolTipText("");
                hideButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hideButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(detailTransactionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listTransactionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(changeButton)
                                .addGap(18, 18, 18)
                                .addComponent(printButton)
                                .addGap(18, 18, 18)
                                .addComponent(hideButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(listTransactionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(detailTransactionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(changeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                        .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5))
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
                xx = evt.getX();
		xy = evt.getY();
        }//GEN-LAST:event_formMousePressed

        private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
               int x,y;
	       x=evt.getXOnScreen();
	       y=evt.getYOnScreen();
	       
	       this.setLocation(x-xx,y-xy);
        }//GEN-LAST:event_formMouseDragged

        private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
                dispose();
        }//GEN-LAST:event_cancelButtonActionPerformed

        private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
                String text = searchField.getText();
		if (text.equals("Masukan Nama Distributor")) {
			searchField.setText("");
			searchField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
                        searchField.setForeground(java.awt.Color.black);
		}
        }//GEN-LAST:event_searchFieldFocusGained

        private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
                String text = searchField.getText();
		if (text.equals("")) {
			searchField.setText("Masukan Nama Distributor");
			searchField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
                        searchField.setForeground(java.awt.Color.gray);
		}
        }//GEN-LAST:event_searchFieldFocusLost

        private void tableTransactionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransactionListMouseClicked
                dataChoose();
        }//GEN-LAST:event_tableTransactionListMouseClicked

        private void tableDetailTransactionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetailTransactionListMouseClicked
                // TODO add your handling code here:
        }//GEN-LAST:event_tableDetailTransactionListMouseClicked

        private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
                editTransaction();
        }//GEN-LAST:event_changeButtonActionPerformed

        private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
                deleteDraft();
		detailTransactionPanel.setVisible(false);
	      changeButton.setVisible(false);
		printButton.setVisible(false);
		hideButton.setVisible(false);
        }//GEN-LAST:event_printButtonActionPerformed

        private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
              detailTransactionPanel.setVisible(false);
	      changeButton.setVisible(false);
		printButton.setVisible(false);
		hideButton.setVisible(false);
        }//GEN-LAST:event_hideButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(listDraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(listDraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(listDraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(listDraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				listDraft dialog = new listDraft(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton cancelButton;
        private javax.swing.JButton changeButton;
        private javax.swing.JPanel detailTransactionPanel;
        private javax.swing.JPanel headerListTransactionPanel;
        private javax.swing.JButton hideButton;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JPanel listTransaction;
        private javax.swing.JPanel listTransactionPanel;
        private javax.swing.JButton printButton;
        private javax.swing.JTextField searchField;
        private javax.swing.JTable tableDetailTransactionList;
        private javax.swing.JTable tableTransactionList;
        // End of variables declaration//GEN-END:variables



//private void searching(){
//	List <modelDistributor>list = service.search(searchField.getText());
//	tabelModel.setData(list);
//}

private void loadData(){
	List<modelCashier>list = service.getItemDrafList();
	tabelModel.setData(list);
}

private void loadDataCart(){
	int row = tableTransactionList.getSelectedRow();
	String id = tableTransactionList.getValueAt(row, 1).toString();
		List <modelDetailCashierDraft> list =servicedetailCashier.getByIdDraft(id);
		tabelModelDetailCashier.setData(list);
}

private void dataChoose(){
	detailTransactionPanel.setVisible(true); 
		changeButton.setVisible(true);
		printButton.setVisible(true);
		hideButton.setVisible(true);
		loadDataCart();
}

	private void editTransaction() {
		int row = tableTransactionList.getSelectedRow();
		String orderIdString = (String) tableTransactionList.getValueAt(row, 1);
		String dateString = (String) tableTransactionList.getValueAt(row, 2);
		List <modelCashierCart> listCart =  servicedetailCashier.getByDraft(orderIdString);
		
			cashierModel.setOrderId(orderIdString);
			cashierModel.setDateOrder(dateString);
			dispose();
	}
	
	private void deleteDraft(){
		int index = tableTransactionList.getSelectedRow();
	       if (index!=-1){
		       modelCashier itemCheckin = tabelModel.getData(tableTransactionList.convertRowIndexToModel(index));
		       modelDetailCashierDraft detail = tabelModelDetailCashier.getData(tableTransactionList.convertRowIndexToModel(index));
		       if (JOptionPane.showConfirmDialog(null, "Apakah ingin menghapus data ini ?","Konfirmasi hapus data",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION) {
			       service.deteleTransactionDraft(itemCheckin);
			       modelDetailCashierDraft detailCheckin= new modelDetailCashierDraft();
			       servicedetailCashier.deleteTransactionDraft(detail);
			       tabelModel.deleteItem(index);
			       loadData();
			       
		       }else{
			       JOptionPane.showMessageDialog(null, "data gagal dihapus");
		       }
	       }
				loadData();
	}

}

